// The site's build channels: one published version of the app per channel, each with its own
// appindex, gallery, hosted web build, and downloads.
//
// A Day repository publishes two of them. The RELEASE channel describes the newest GitHub
// release and is assembled entirely from assets that release already carries — the packages, the
// screenshots zip, the web-dom dist. The MAIN channel describes the newest build of the default
// branch and is assembled from the artifacts the CI run just produced, which is why its pages
// carry a development-build notice and its downloads are served from the site itself rather than
// from a release that does not exist yet.
//
// The default channel owns the locale root (`/en/`); every other channel lives one segment
// deeper (`/en/main/`) with a full duplicate of the pages, screenshots, and download links. A
// repository with no release at all publishes main as the default, and the version picker,
// having one entry, is not drawn.
//
// `channels.json` is written beside site.toml by scripts/generate-site.mjs. Without one — a
// local `preview.mjs` run, an older app repository — the site has exactly one channel built from
// site.toml's own `appindex` key, which is the layout every daysite had before channels existed.

import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

/** One channel, as scripts/generate-site.mjs records it in channels.json. */
export interface ChannelRecord {
  /** Stable identifier: `release` or `main`. */
  id: string;
  /** Picker label: the release's version (`0.4.1`) or the branch name (`main`). */
  label: string;
  /**
   * URL segment between the locale and the page, without slashes. Empty for the default
   * channel, which owns the locale root.
   */
  path: string;
  /**
   * An extra segment that redirects to this channel. The default channel keeps its natural
   * segment reachable this way, so `/en/main/` resolves whether or not a release exists.
   */
  alias?: string;
  /** True for a build of a branch rather than a published release. */
  development: boolean;
  /** appindex.json for this channel, relative to site.toml. */
  appindex: string;
  /** gallery-manifest.json for this channel, relative to site.toml. */
  gallery: string;
  /** Directory under the site root holding this channel's web-dom build (`main/webapp`). */
  webapp: string;
  /** Release tag, for a release channel (`v0.4.1`). */
  tag?: string;
  /** The GitHub release page. */
  releaseURL?: string;
  /** Branch name, for a development channel. */
  ref?: string;
  /** Short commit the development build came from. */
  commit?: string;
  /** The commit's page on GitHub. */
  commitURL?: string;
  /** The CI run that produced the development build. */
  runURL?: string;
}

export interface ChannelsFile {
  /** `id` of the channel that owns the locale root. */
  default: string;
  channels: ChannelRecord[];
}

/** A channel resolved for rendering: the record, plus where it sits relative to the page. */
export interface ChannelView extends ChannelRecord {
  /** True when this is the channel the current page renders. */
  current: boolean;
}

/**
 * The channels declared beside site.toml, in picker order (release first). Returns a single
 * implicit channel when there is no channels.json, so a site generated by the older
 * two-script path renders exactly as it did.
 */
export async function loadChannels(
  siteInfoFile: string,
  fallbackAppindex: string,
  fallbackWebapp: string,
): Promise<ChannelsFile> {
  const path = join(dirname(siteInfoFile), 'channels.json');
  if (existsSync(path)) {
    const parsed = JSON.parse(await readFile(path, 'utf8')) as ChannelsFile;
    if (parsed.channels?.length) return parsed;
  }
  return {
    default: 'release',
    channels: [
      {
        id: 'release',
        label: '',
        path: '',
        development: false,
        appindex: fallbackAppindex,
        gallery: 'gallery-manifest.json',
        webapp: fallbackWebapp,
      },
    ],
  };
}

/** The channel a page renders, by id; the default channel when the id is unknown or absent. */
export function pickChannel(file: ChannelsFile, id?: string): ChannelRecord {
  return (
    (id ? file.channels.find((c) => c.id === id) : undefined) ??
    file.channels.find((c) => c.id === file.default) ??
    file.channels[0]!
  );
}
