/**
 * Canonical localized strings for permissions:
 *
 *  - PERMISSION_LABELS — short display names ("Camera", "Microphone", …)
 *    keyed by their canonical English form. Used for the title shown on each
 *    permission card.
 *
 *  - ANDROID_PERMISSION_DESCRIPTIONS — one-sentence descriptions for Android
 *    permissions, paraphrased from the official platform documentation
 *    (https://developer.android.com/reference/android/Manifest.permission).
 *    Used as a fallback rationale when the appindex.json doesn't supply a
 *    per-app description for an Android permission.
 *
 * Both tables fall back through: requested locale → language-only →
 * regional sibling → en → first defined.
 */

export type LocalizedString = Record<string, string>;

// -----------------------------------------------------------------------------
// Permission display names
// -----------------------------------------------------------------------------

export const PERMISSION_LABELS: Record<string, LocalizedString> = {
  // Hardware sensors & I/O ────────────────────────────────────────────────────
  Camera: {
    en: 'Camera', ar: 'الكاميرا', de: 'Kamera', es: 'Cámara', fr: 'Appareil photo',
    hi: 'कैमरा', id: 'Kamera', it: 'Fotocamera', ja: 'カメラ', ko: '카메라',
    'pt-BR': 'Câmera', ru: 'Камера', 'zh-CN': '相机',
  },
  Microphone: {
    en: 'Microphone', ar: 'الميكروفون', de: 'Mikrofon', es: 'Micrófono', fr: 'Microphone',
    hi: 'माइक्रोफ़ोन', id: 'Mikrofon', it: 'Microfono', ja: 'マイク', ko: '마이크',
    'pt-BR': 'Microfone', ru: 'Микрофон', 'zh-CN': '麦克风',
  },
  Bluetooth: {
    en: 'Bluetooth', ar: 'البلوتوث', de: 'Bluetooth', es: 'Bluetooth', fr: 'Bluetooth',
    hi: 'ब्लूटूथ', id: 'Bluetooth', it: 'Bluetooth', ja: 'Bluetooth', ko: '블루투스',
    'pt-BR': 'Bluetooth', ru: 'Bluetooth', 'zh-CN': '蓝牙',
  },
  'Bluetooth peripheral': {
    en: 'Bluetooth peripheral', ar: 'جهاز بلوتوث طرفي', de: 'Bluetooth-Peripheriegerät',
    es: 'Periférico Bluetooth', fr: 'Périphérique Bluetooth',
    hi: 'ब्लूटूथ पेरिफेरल', id: 'Periferal Bluetooth', it: 'Periferica Bluetooth',
    ja: 'Bluetooth 周辺機器', ko: '블루투스 주변기기',
    'pt-BR': 'Periférico Bluetooth', ru: 'Периферия Bluetooth', 'zh-CN': '蓝牙外设',
  },
  'Bluetooth admin': {
    en: 'Bluetooth admin', ar: 'إدارة البلوتوث', de: 'Bluetooth-Verwaltung',
    es: 'Administración Bluetooth', fr: 'Administration Bluetooth',
    hi: 'ब्लूटूथ व्यवस्थापन', id: 'Admin Bluetooth', it: 'Amministrazione Bluetooth',
    ja: 'Bluetooth 管理', ko: '블루투스 관리',
    'pt-BR': 'Administração de Bluetooth', ru: 'Управление Bluetooth', 'zh-CN': '蓝牙管理',
  },
  'Bluetooth advertise': {
    en: 'Bluetooth advertise', ar: 'إعلان البلوتوث', de: 'Bluetooth-Werbung',
    es: 'Anunciar por Bluetooth', fr: 'Annonce Bluetooth',
    hi: 'ब्लूटूथ विज्ञापन', id: 'Iklan Bluetooth', it: 'Annuncio Bluetooth',
    ja: 'Bluetooth アドバタイズ', ko: '블루투스 광고',
    'pt-BR': 'Anúncio Bluetooth', ru: 'Анонсирование Bluetooth', 'zh-CN': '蓝牙广播',
  },
  'Bluetooth connect': {
    en: 'Bluetooth connect', ar: 'اتصال البلوتوث', de: 'Bluetooth-Verbindung',
    es: 'Conexión Bluetooth', fr: 'Connexion Bluetooth',
    hi: 'ब्लूटूथ कनेक्ट', id: 'Sambungan Bluetooth', it: 'Connessione Bluetooth',
    ja: 'Bluetooth 接続', ko: '블루투스 연결',
    'pt-BR': 'Conexão Bluetooth', ru: 'Подключение Bluetooth', 'zh-CN': '蓝牙连接',
  },
  'Bluetooth scan': {
    en: 'Bluetooth scan', ar: 'فحص البلوتوث', de: 'Bluetooth-Suche',
    es: 'Escaneo Bluetooth', fr: 'Recherche Bluetooth',
    hi: 'ब्लूटूथ स्कैन', id: 'Pemindaian Bluetooth', it: 'Scansione Bluetooth',
    ja: 'Bluetooth スキャン', ko: '블루투스 검색',
    'pt-BR': 'Busca Bluetooth', ru: 'Поиск Bluetooth', 'zh-CN': '蓝牙扫描',
  },
  NFC: {
    en: 'NFC', ar: 'NFC', de: 'NFC', es: 'NFC', fr: 'NFC',
    hi: 'NFC', id: 'NFC', it: 'NFC', ja: 'NFC', ko: 'NFC',
    'pt-BR': 'NFC', ru: 'NFC', 'zh-CN': 'NFC',
  },
  'NFC reader': {
    en: 'NFC reader', ar: 'قارئ NFC', de: 'NFC-Leser',
    es: 'Lector NFC', fr: 'Lecteur NFC',
    hi: 'NFC रीडर', id: 'Pembaca NFC', it: 'Lettore NFC',
    ja: 'NFC リーダー', ko: 'NFC 리더',
    'pt-BR': 'Leitor NFC', ru: 'Считыватель NFC', 'zh-CN': 'NFC 读取器',
  },
  'NFC transactions': {
    en: 'NFC transactions', ar: 'معاملات NFC', de: 'NFC-Transaktionen',
    es: 'Transacciones NFC', fr: 'Transactions NFC',
    hi: 'NFC लेनदेन', id: 'Transaksi NFC', it: 'Transazioni NFC',
    ja: 'NFC 取引', ko: 'NFC 거래',
    'pt-BR': 'Transações NFC', ru: 'Операции NFC', 'zh-CN': 'NFC 交易',
  },
  'NFC payment info': {
    en: 'NFC payment info', ar: 'معلومات دفع NFC', de: 'NFC-Zahlungsinfos',
    es: 'Información de pago NFC', fr: 'Infos de paiement NFC',
    hi: 'NFC भुगतान जानकारी', id: 'Info pembayaran NFC', it: 'Info pagamento NFC',
    ja: 'NFC 決済情報', ko: 'NFC 결제 정보',
    'pt-BR': 'Informações de pagamento NFC', ru: 'Сведения о платеже NFC', 'zh-CN': 'NFC 付款信息',
  },
  'Use infrared': {
    en: 'Use infrared', ar: 'استخدام الأشعة تحت الحمراء', de: 'Infrarot verwenden',
    es: 'Usar infrarrojos', fr: 'Utiliser l’infrarouge',
    hi: 'इन्फ़्रारेड का उपयोग', id: 'Gunakan inframerah', it: 'Usa infrarossi',
    ja: '赤外線の使用', ko: '적외선 사용',
    'pt-BR': 'Usar infravermelho', ru: 'Инфракрасный порт', 'zh-CN': '使用红外',
  },
  Vibration: {
    en: 'Vibration', ar: 'الاهتزاز', de: 'Vibration', es: 'Vibración', fr: 'Vibration',
    hi: 'कंपन', id: 'Getaran', it: 'Vibrazione', ja: 'バイブレーション', ko: '진동',
    'pt-BR': 'Vibração', ru: 'Вибрация', 'zh-CN': '振动',
  },
  'Body sensors': {
    en: 'Body sensors', ar: 'مستشعرات الجسم', de: 'Körpersensoren',
    es: 'Sensores corporales', fr: 'Capteurs corporels',
    hi: 'शरीर के सेंसर', id: 'Sensor tubuh', it: 'Sensori corporei',
    ja: '身体センサー', ko: '신체 센서',
    'pt-BR': 'Sensores corporais', ru: 'Датчики тела', 'zh-CN': '身体传感器',
  },
  'Body sensors (background)': {
    en: 'Body sensors (background)', ar: 'مستشعرات الجسم (في الخلفية)',
    de: 'Körpersensoren (Hintergrund)', es: 'Sensores corporales (segundo plano)',
    fr: 'Capteurs corporels (arrière-plan)',
    hi: 'शरीर के सेंसर (पृष्ठभूमि)', id: 'Sensor tubuh (latar belakang)',
    it: 'Sensori corporei (in background)', ja: '身体センサー (バックグラウンド)',
    ko: '신체 센서 (백그라운드)', 'pt-BR': 'Sensores corporais (em segundo plano)',
    ru: 'Датчики тела (в фоне)', 'zh-CN': '身体传感器（后台）',
  },
  SensorKit: {
    en: 'SensorKit', ar: 'SensorKit', de: 'SensorKit', es: 'SensorKit', fr: 'SensorKit',
    hi: 'SensorKit', id: 'SensorKit', it: 'SensorKit', ja: 'SensorKit', ko: 'SensorKit',
    'pt-BR': 'SensorKit', ru: 'SensorKit', 'zh-CN': 'SensorKit',
  },
  'High-rate sensors': {
    en: 'High-rate sensors', ar: 'مستشعرات بمعدل عالٍ', de: 'Hochfrequente Sensoren',
    es: 'Sensores de alta frecuencia', fr: 'Capteurs haute fréquence',
    hi: 'उच्च-दर सेंसर', id: 'Sensor laju tinggi', it: 'Sensori ad alta frequenza',
    ja: '高サンプリングレートのセンサー', ko: '고주기 센서',
    'pt-BR': 'Sensores de alta taxa', ru: 'Высокочастотные датчики', 'zh-CN': '高采样率传感器',
  },

  // Personal data ─────────────────────────────────────────────────────────────
  Contacts: {
    en: 'Contacts', ar: 'جهات الاتصال', de: 'Kontakte', es: 'Contactos', fr: 'Contacts',
    hi: 'संपर्क', id: 'Kontak', it: 'Contatti', ja: '連絡先', ko: '연락처',
    'pt-BR': 'Contatos', ru: 'Контакты', 'zh-CN': '通讯录',
  },
  'Read contacts': {
    en: 'Read contacts', ar: 'قراءة جهات الاتصال', de: 'Kontakte lesen',
    es: 'Leer contactos', fr: 'Lire les contacts',
    hi: 'संपर्क पढ़ें', id: 'Baca kontak', it: 'Leggi contatti',
    ja: '連絡先の読み取り', ko: '연락처 읽기',
    'pt-BR': 'Ler contatos', ru: 'Чтение контактов', 'zh-CN': '读取联系人',
  },
  'Write contacts': {
    en: 'Write contacts', ar: 'كتابة جهات الاتصال', de: 'Kontakte schreiben',
    es: 'Escribir contactos', fr: 'Modifier les contacts',
    hi: 'संपर्क संशोधित करें', id: 'Tulis kontak', it: 'Modifica contatti',
    ja: '連絡先の書き込み', ko: '연락처 쓰기',
    'pt-BR': 'Modificar contatos', ru: 'Запись контактов', 'zh-CN': '修改联系人',
  },
  Calendar: {
    en: 'Calendar', ar: 'التقويم', de: 'Kalender', es: 'Calendario', fr: 'Calendrier',
    hi: 'कैलेंडर', id: 'Kalender', it: 'Calendario', ja: 'カレンダー', ko: '캘린더',
    'pt-BR': 'Calendário', ru: 'Календарь', 'zh-CN': '日历',
  },
  'Calendar (full access)': {
    en: 'Calendar (full access)', ar: 'التقويم (وصول كامل)',
    de: 'Kalender (Vollzugriff)', es: 'Calendario (acceso completo)',
    fr: 'Calendrier (accès complet)', hi: 'कैलेंडर (पूर्ण पहुँच)',
    id: 'Kalender (akses penuh)', it: 'Calendario (accesso completo)',
    ja: 'カレンダー (フルアクセス)', ko: '캘린더 (전체 접근)',
    'pt-BR': 'Calendário (acesso completo)', ru: 'Календарь (полный доступ)',
    'zh-CN': '日历（完全访问）',
  },
  'Calendar (write)': {
    en: 'Calendar (write)', ar: 'التقويم (كتابة)',
    de: 'Kalender (Schreibzugriff)', es: 'Calendario (escritura)',
    fr: 'Calendrier (écriture)', hi: 'कैलेंडर (लिखें)',
    id: 'Kalender (tulis)', it: 'Calendario (scrittura)',
    ja: 'カレンダー (書き込み)', ko: '캘린더 (쓰기)',
    'pt-BR': 'Calendário (gravação)', ru: 'Календарь (запись)',
    'zh-CN': '日历（写入）',
  },
  'Read calendar': {
    en: 'Read calendar', ar: 'قراءة التقويم', de: 'Kalender lesen',
    es: 'Leer calendario', fr: 'Lire le calendrier',
    hi: 'कैलेंडर पढ़ें', id: 'Baca kalender', it: 'Leggi calendario',
    ja: 'カレンダーの読み取り', ko: '캘린더 읽기',
    'pt-BR': 'Ler calendário', ru: 'Чтение календаря', 'zh-CN': '读取日历',
  },
  'Write calendar': {
    en: 'Write calendar', ar: 'كتابة التقويم', de: 'Kalender schreiben',
    es: 'Modificar calendario', fr: 'Modifier le calendrier',
    hi: 'कैलेंडर संशोधित करें', id: 'Tulis kalender', it: 'Modifica calendario',
    ja: 'カレンダーの書き込み', ko: '캘린더 쓰기',
    'pt-BR': 'Modificar calendário', ru: 'Запись в календарь', 'zh-CN': '修改日历',
  },
  Reminders: {
    en: 'Reminders', ar: 'التذكيرات', de: 'Erinnerungen', es: 'Recordatorios',
    fr: 'Rappels', hi: 'अनुस्मारक', id: 'Pengingat', it: 'Promemoria',
    ja: 'リマインダー', ko: '미리 알림',
    'pt-BR': 'Lembretes', ru: 'Напоминания', 'zh-CN': '提醒事项',
  },
  'Reminders (full access)': {
    en: 'Reminders (full access)', ar: 'التذكيرات (وصول كامل)',
    de: 'Erinnerungen (Vollzugriff)', es: 'Recordatorios (acceso completo)',
    fr: 'Rappels (accès complet)', hi: 'अनुस्मारक (पूर्ण पहुँच)',
    id: 'Pengingat (akses penuh)', it: 'Promemoria (accesso completo)',
    ja: 'リマインダー (フルアクセス)', ko: '미리 알림 (전체 접근)',
    'pt-BR': 'Lembretes (acesso completo)', ru: 'Напоминания (полный доступ)',
    'zh-CN': '提醒事项（完全访问）',
  },

  // Photos & media ────────────────────────────────────────────────────────────
  'Photo library': {
    en: 'Photo library', ar: 'مكتبة الصور', de: 'Fotomediathek',
    es: 'Fototeca', fr: 'Photothèque',
    hi: 'फ़ोटो लाइब्रेरी', id: 'Pustaka foto', it: 'Libreria foto',
    ja: '写真ライブラリ', ko: '사진 보관함',
    'pt-BR': 'Biblioteca de fotos', ru: 'Медиатека', 'zh-CN': '照片图库',
  },
  'Save to photos': {
    en: 'Save to photos', ar: 'الحفظ إلى الصور', de: 'In Fotos sichern',
    es: 'Guardar en fotos', fr: 'Enregistrer dans Photos',
    hi: 'फ़ोटो में सहेजें', id: 'Simpan ke foto', it: 'Salva nelle foto',
    ja: '写真に保存', ko: '사진에 저장',
    'pt-BR': 'Salvar em fotos', ru: 'Сохранить в Фото', 'zh-CN': '保存到照片',
  },
  'Read images': {
    en: 'Read images', ar: 'قراءة الصور', de: 'Bilder lesen',
    es: 'Leer imágenes', fr: 'Lire les images',
    hi: 'छवियाँ पढ़ें', id: 'Baca gambar', it: 'Leggi immagini',
    ja: '画像の読み取り', ko: '이미지 읽기',
    'pt-BR': 'Ler imagens', ru: 'Чтение изображений', 'zh-CN': '读取图片',
  },
  'Read video': {
    en: 'Read video', ar: 'قراءة الفيديو', de: 'Video lesen',
    es: 'Leer vídeo', fr: 'Lire les vidéos',
    hi: 'वीडियो पढ़ें', id: 'Baca video', it: 'Leggi video',
    ja: '動画の読み取り', ko: '동영상 읽기',
    'pt-BR': 'Ler vídeos', ru: 'Чтение видео', 'zh-CN': '读取视频',
  },
  'Read audio': {
    en: 'Read audio', ar: 'قراءة الصوت', de: 'Audio lesen',
    es: 'Leer audio', fr: 'Lire l’audio',
    hi: 'ऑडियो पढ़ें', id: 'Baca audio', it: 'Leggi audio',
    ja: '音声の読み取り', ko: '오디오 읽기',
    'pt-BR': 'Ler áudio', ru: 'Чтение аудио', 'zh-CN': '读取音频',
  },
  'Selected media': {
    en: 'Selected media', ar: 'الوسائط المحددة', de: 'Ausgewählte Medien',
    es: 'Medios seleccionados', fr: 'Médias sélectionnés',
    hi: 'चयनित मीडिया', id: 'Media yang dipilih', it: 'Contenuti selezionati',
    ja: '選択したメディア', ko: '선택한 미디어',
    'pt-BR': 'Mídia selecionada', ru: 'Выбранные медиафайлы', 'zh-CN': '已选媒体',
  },
  'Manage media': {
    en: 'Manage media', ar: 'إدارة الوسائط', de: 'Medien verwalten',
    es: 'Gestionar medios', fr: 'Gérer les médias',
    hi: 'मीडिया प्रबंधन', id: 'Kelola media', it: 'Gestisci media',
    ja: 'メディアの管理', ko: '미디어 관리',
    'pt-BR': 'Gerenciar mídia', ru: 'Управление медиа', 'zh-CN': '管理媒体',
  },
  'Apple Music': {
    en: 'Apple Music', ar: 'Apple Music', de: 'Apple Music', es: 'Apple Music',
    fr: 'Apple Music', hi: 'Apple Music', id: 'Apple Music', it: 'Apple Music',
    ja: 'Apple Music', ko: 'Apple Music', 'pt-BR': 'Apple Music',
    ru: 'Apple Music', 'zh-CN': 'Apple Music',
  },
  'Media content control': {
    en: 'Media content control', ar: 'التحكم بمحتوى الوسائط',
    de: 'Mediensteuerung', es: 'Control de contenido multimedia',
    fr: 'Contrôle des médias', hi: 'मीडिया सामग्री नियंत्रण',
    id: 'Kontrol konten media', it: 'Controllo contenuti multimediali',
    ja: 'メディア再生の制御', ko: '미디어 콘텐츠 제어',
    'pt-BR': 'Controle de conteúdo de mídia', ru: 'Управление медиаконтентом',
    'zh-CN': '媒体内容控制',
  },

  // Location ──────────────────────────────────────────────────────────────────
  Location: {
    en: 'Location', ar: 'الموقع', de: 'Standort', es: 'Ubicación', fr: 'Position',
    hi: 'स्थान', id: 'Lokasi', it: 'Posizione', ja: '位置情報', ko: '위치',
    'pt-BR': 'Localização', ru: 'Местоположение', 'zh-CN': '位置',
  },
  'Location (in use)': {
    en: 'Location (in use)', ar: 'الموقع (أثناء الاستخدام)',
    de: 'Standort (bei Nutzung)', es: 'Ubicación (en uso)',
    fr: 'Position (en cours d’utilisation)', hi: 'स्थान (उपयोग के दौरान)',
    id: 'Lokasi (saat digunakan)', it: 'Posizione (in uso)',
    ja: '位置情報 (使用中)', ko: '위치 (사용 중)',
    'pt-BR': 'Localização (em uso)', ru: 'Местоположение (при использовании)',
    'zh-CN': '位置（使用期间）',
  },
  'Location (always)': {
    en: 'Location (always)', ar: 'الموقع (دائماً)',
    de: 'Standort (immer)', es: 'Ubicación (siempre)',
    fr: 'Position (toujours)', hi: 'स्थान (हमेशा)',
    id: 'Lokasi (selalu)', it: 'Posizione (sempre)',
    ja: '位置情報 (常に)', ko: '위치 (항상)',
    'pt-BR': 'Localização (sempre)', ru: 'Местоположение (всегда)',
    'zh-CN': '位置（始终）',
  },
  'Location (temporary)': {
    en: 'Location (temporary)', ar: 'الموقع (مؤقت)',
    de: 'Standort (temporär)', es: 'Ubicación (temporal)',
    fr: 'Position (temporaire)', hi: 'स्थान (अस्थायी)',
    id: 'Lokasi (sementara)', it: 'Posizione (temporanea)',
    ja: '位置情報 (一時的)', ko: '위치 (일시적)',
    'pt-BR': 'Localização (temporária)', ru: 'Местоположение (временно)',
    'zh-CN': '位置（临时）',
  },
  'Background location': {
    en: 'Background location', ar: 'الموقع في الخلفية',
    de: 'Standort im Hintergrund', es: 'Ubicación en segundo plano',
    fr: 'Position en arrière-plan', hi: 'पृष्ठभूमि स्थान',
    id: 'Lokasi latar belakang', it: 'Posizione in background',
    ja: 'バックグラウンドの位置情報', ko: '백그라운드 위치',
    'pt-BR': 'Localização em segundo plano', ru: 'Местоположение в фоне',
    'zh-CN': '后台位置',
  },
  'Approximate location': {
    en: 'Approximate location', ar: 'الموقع التقريبي',
    de: 'Ungefährer Standort', es: 'Ubicación aproximada',
    fr: 'Position approximative', hi: 'अनुमानित स्थान',
    id: 'Perkiraan lokasi', it: 'Posizione approssimativa',
    ja: 'おおよその位置情報', ko: '대략적인 위치',
    'pt-BR': 'Localização aproximada', ru: 'Приблизительное местоположение',
    'zh-CN': '大致位置',
  },
  'Precise location': {
    en: 'Precise location', ar: 'الموقع الدقيق',
    de: 'Genauer Standort', es: 'Ubicación precisa',
    fr: 'Position précise', hi: 'सटीक स्थान',
    id: 'Lokasi tepat', it: 'Posizione precisa',
    ja: '正確な位置情報', ko: '정확한 위치',
    'pt-BR': 'Localização precisa', ru: 'Точное местоположение',
    'zh-CN': '精确位置',
  },

  // Networking ────────────────────────────────────────────────────────────────
  Internet: {
    en: 'Internet', ar: 'الإنترنت', de: 'Internet', es: 'Internet', fr: 'Internet',
    hi: 'इंटरनेट', id: 'Internet', it: 'Internet', ja: 'インターネット',
    ko: '인터넷', 'pt-BR': 'Internet', ru: 'Интернет', 'zh-CN': '互联网',
  },
  'Network state': {
    en: 'Network state', ar: 'حالة الشبكة', de: 'Netzwerkstatus',
    es: 'Estado de red', fr: 'État du réseau',
    hi: 'नेटवर्क स्थिति', id: 'Status jaringan', it: 'Stato rete',
    ja: 'ネットワーク状態', ko: '네트워크 상태',
    'pt-BR': 'Estado da rede', ru: 'Состояние сети', 'zh-CN': '网络状态',
  },
  'Change network state': {
    en: 'Change network state', ar: 'تغيير حالة الشبكة', de: 'Netzwerkstatus ändern',
    es: 'Cambiar estado de red', fr: 'Modifier l’état du réseau',
    hi: 'नेटवर्क स्थिति बदलें', id: 'Ubah status jaringan', it: 'Cambia stato rete',
    ja: 'ネットワーク状態の変更', ko: '네트워크 상태 변경',
    'pt-BR': 'Alterar estado da rede', ru: 'Изменение состояния сети',
    'zh-CN': '更改网络状态',
  },
  'Wi-Fi state': {
    en: 'Wi-Fi state', ar: 'حالة Wi-Fi', de: 'WLAN-Status',
    es: 'Estado de Wi-Fi', fr: 'État Wi-Fi',
    hi: 'वाई-फ़ाई स्थिति', id: 'Status Wi-Fi', it: 'Stato Wi-Fi',
    ja: 'Wi-Fi の状態', ko: 'Wi-Fi 상태',
    'pt-BR': 'Estado do Wi-Fi', ru: 'Состояние Wi-Fi', 'zh-CN': 'Wi-Fi 状态',
  },
  'Change Wi-Fi state': {
    en: 'Change Wi-Fi state', ar: 'تغيير حالة Wi-Fi', de: 'WLAN-Status ändern',
    es: 'Cambiar estado de Wi-Fi', fr: 'Modifier l’état du Wi-Fi',
    hi: 'वाई-फ़ाई स्थिति बदलें', id: 'Ubah status Wi-Fi', it: 'Cambia stato Wi-Fi',
    ja: 'Wi-Fi 状態の変更', ko: 'Wi-Fi 상태 변경',
    'pt-BR': 'Alterar estado do Wi-Fi', ru: 'Изменение состояния Wi-Fi',
    'zh-CN': '更改 Wi-Fi 状态',
  },
  'Wi-Fi multicast': {
    en: 'Wi-Fi multicast', ar: 'البث المتعدد لـ Wi-Fi', de: 'WLAN-Multicast',
    es: 'Multidifusión Wi-Fi', fr: 'Multidiffusion Wi-Fi',
    hi: 'वाई-फ़ाई मल्टीकास्ट', id: 'Multicast Wi-Fi', it: 'Multicast Wi-Fi',
    ja: 'Wi-Fi マルチキャスト', ko: 'Wi-Fi 멀티캐스트',
    'pt-BR': 'Multicast Wi-Fi', ru: 'Многоадресная рассылка Wi-Fi',
    'zh-CN': 'Wi-Fi 组播',
  },
  'Nearby Wi-Fi devices': {
    en: 'Nearby Wi-Fi devices', ar: 'أجهزة Wi-Fi القريبة',
    de: 'Nahe WLAN-Geräte', es: 'Dispositivos Wi-Fi cercanos',
    fr: 'Appareils Wi-Fi à proximité', hi: 'पास के वाई-फ़ाई डिवाइस',
    id: 'Perangkat Wi-Fi terdekat', it: 'Dispositivi Wi-Fi vicini',
    ja: '近くの Wi-Fi 機器', ko: '주변 Wi-Fi 기기',
    'pt-BR': 'Dispositivos Wi-Fi próximos', ru: 'Устройства Wi-Fi рядом',
    'zh-CN': '附近的 Wi-Fi 设备',
  },
  'Local network': {
    en: 'Local network', ar: 'الشبكة المحلية', de: 'Lokales Netzwerk',
    es: 'Red local', fr: 'Réseau local',
    hi: 'स्थानीय नेटवर्क', id: 'Jaringan lokal', it: 'Rete locale',
    ja: 'ローカルネットワーク', ko: '로컬 네트워크',
    'pt-BR': 'Rede local', ru: 'Локальная сеть', 'zh-CN': '本地网络',
  },
  'Nearby interaction': {
    en: 'Nearby interaction', ar: 'التفاعل القريب', de: 'Nahinteraktion',
    es: 'Interacción cercana', fr: 'Interaction à proximité',
    hi: 'निकट इंटरैक्शन', id: 'Interaksi dekat', it: 'Interazione ravvicinata',
    ja: '近接インタラクション', ko: '근접 상호작용',
    'pt-BR': 'Interação por proximidade', ru: 'Ближнее взаимодействие',
    'zh-CN': '近距离互动',
  },
  'UWB ranging': {
    en: 'UWB ranging', ar: 'قياس المسافة عبر UWB',
    de: 'UWB-Entfernungsmessung', es: 'Medición UWB',
    fr: 'Mesure UWB', hi: 'UWB रेंजिंग',
    id: 'Pengukuran UWB', it: 'Misurazione UWB',
    ja: 'UWB レンジング', ko: 'UWB 거리 측정',
    'pt-BR': 'Medição UWB', ru: 'Измерение расстояния UWB',
    'zh-CN': 'UWB 测距',
  },

  // Authentication & security ────────────────────────────────────────────────
  'Face ID': {
    en: 'Face ID', ar: 'Face ID', de: 'Face ID', es: 'Face ID', fr: 'Face ID',
    hi: 'Face ID', id: 'Face ID', it: 'Face ID', ja: 'Face ID', ko: 'Face ID',
    'pt-BR': 'Face ID', ru: 'Face ID', 'zh-CN': '面容 ID',
  },
  Biometrics: {
    en: 'Biometrics', ar: 'القياسات الحيوية', de: 'Biometrie',
    es: 'Biometría', fr: 'Biométrie',
    hi: 'बायोमेट्रिक्स', id: 'Biometrik', it: 'Biometria',
    ja: '生体認証', ko: '생체 인증',
    'pt-BR': 'Biometria', ru: 'Биометрия', 'zh-CN': '生物识别',
  },
  Fingerprint: {
    en: 'Fingerprint', ar: 'بصمة الإصبع', de: 'Fingerabdruck',
    es: 'Huella dactilar', fr: 'Empreinte digitale',
    hi: 'फ़िंगरप्रिंट', id: 'Sidik jari', it: 'Impronta digitale',
    ja: '指紋', ko: '지문',
    'pt-BR': 'Impressão digital', ru: 'Отпечаток пальца', 'zh-CN': '指纹',
  },
  Identity: {
    en: 'Identity', ar: 'الهوية', de: 'Identität', es: 'Identidad',
    fr: 'Identité', hi: 'पहचान', id: 'Identitas', it: 'Identità',
    ja: 'ID', ko: '신원', 'pt-BR': 'Identidade', ru: 'Личность',
    'zh-CN': '身份',
  },
  'Disable keyguard': {
    en: 'Disable keyguard', ar: 'تعطيل قفل الشاشة',
    de: 'Tastensperre deaktivieren', es: 'Desactivar bloqueo',
    fr: 'Désactiver le verrouillage', hi: 'कीगार्ड अक्षम करें',
    id: 'Nonaktifkan kunci layar', it: 'Disattiva blocco schermo',
    ja: 'キーガードの無効化', ko: '잠금화면 비활성화',
    'pt-BR': 'Desativar tela de bloqueio', ru: 'Отключение блокировки',
    'zh-CN': '禁用锁屏',
  },
  'Password requirements': {
    en: 'Password requirements', ar: 'متطلبات كلمة المرور',
    de: 'Passwortanforderungen', es: 'Requisitos de contraseña',
    fr: 'Exigences de mot de passe', hi: 'पासवर्ड आवश्यकताएँ',
    id: 'Persyaratan kata sandi', it: 'Requisiti password',
    ja: 'パスワード要件', ko: '비밀번호 요구사항',
    'pt-BR': 'Requisitos de senha', ru: 'Требования к паролю',
    'zh-CN': '密码要求',
  },

  // Phone ─────────────────────────────────────────────────────────────────────
  'Phone state': {
    en: 'Phone state', ar: 'حالة الهاتف', de: 'Telefonstatus',
    es: 'Estado del teléfono', fr: 'État du téléphone',
    hi: 'फ़ोन स्थिति', id: 'Status telepon', it: 'Stato telefono',
    ja: '電話の状態', ko: '전화 상태',
    'pt-BR': 'Estado do telefone', ru: 'Состояние телефона',
    'zh-CN': '电话状态',
  },
  'Basic phone state': {
    en: 'Basic phone state', ar: 'حالة الهاتف الأساسية',
    de: 'Grundlegender Telefonstatus', es: 'Estado básico del teléfono',
    fr: 'État de base du téléphone', hi: 'मूल फ़ोन स्थिति',
    id: 'Status dasar telepon', it: 'Stato base telefono',
    ja: '基本的な電話の状態', ko: '기본 전화 상태',
    'pt-BR': 'Estado básico do telefone', ru: 'Базовое состояние телефона',
    'zh-CN': '基本电话状态',
  },
  'Phone number': {
    en: 'Phone number', ar: 'رقم الهاتف', de: 'Telefonnummer',
    es: 'Número de teléfono', fr: 'Numéro de téléphone',
    hi: 'फ़ोन नंबर', id: 'Nomor telepon', it: 'Numero di telefono',
    ja: '電話番号', ko: '전화번호',
    'pt-BR': 'Número de telefone', ru: 'Номер телефона',
    'zh-CN': '电话号码',
  },
  'Make calls': {
    en: 'Make calls', ar: 'إجراء المكالمات', de: 'Anrufe tätigen',
    es: 'Realizar llamadas', fr: 'Passer des appels',
    hi: 'कॉल करें', id: 'Lakukan panggilan', it: 'Effettua chiamate',
    ja: '電話の発信', ko: '전화 걸기',
    'pt-BR': 'Fazer chamadas', ru: 'Совершение вызовов', 'zh-CN': '拨打电话',
  },
  'Answer calls': {
    en: 'Answer calls', ar: 'الرد على المكالمات', de: 'Anrufe annehmen',
    es: 'Responder llamadas', fr: 'Répondre aux appels',
    hi: 'कॉल का उत्तर दें', id: 'Jawab panggilan', it: 'Rispondi alle chiamate',
    ja: '電話への応答', ko: '전화 받기',
    'pt-BR': 'Atender chamadas', ru: 'Ответ на звонки', 'zh-CN': '接听电话',
  },
  'Manage own calls': {
    en: 'Manage own calls', ar: 'إدارة مكالمات التطبيق',
    de: 'Eigene Anrufe verwalten', es: 'Gestionar llamadas propias',
    fr: 'Gérer ses propres appels', hi: 'खुद की कॉल प्रबंधन',
    id: 'Kelola panggilan sendiri', it: 'Gestisci chiamate proprie',
    ja: 'アプリ内通話の管理', ko: '자체 통화 관리',
    'pt-BR': 'Gerenciar chamadas próprias', ru: 'Управление вызовами приложения',
    'zh-CN': '管理自身通话',
  },
  'Accept call handover': {
    en: 'Accept call handover', ar: 'قبول تحويل المكالمة',
    de: 'Anrufübergabe annehmen', es: 'Aceptar traspaso de llamada',
    fr: 'Accepter le transfert d’appel', hi: 'कॉल हैंडओवर स्वीकार करें',
    id: 'Terima alih panggilan', it: 'Accetta passaggio chiamata',
    ja: '通話の引き継ぎを受け入れる', ko: '통화 전환 수락',
    'pt-BR': 'Aceitar transferência de chamada', ru: 'Принять передачу звонка',
    'zh-CN': '接受通话切换',
  },
  'Call companion app': {
    en: 'Call companion app', ar: 'تطبيق مصاحب للمكالمات',
    de: 'Begleit-App für Anrufe', es: 'App de acompañamiento de llamadas',
    fr: 'App compagnon d’appel', hi: 'कॉल साथी ऐप',
    id: 'Aplikasi pendamping panggilan', it: 'App accompagnatrice chiamate',
    ja: '通話コンパニオン アプリ', ko: '통화 컴패니언 앱',
    'pt-BR': 'App complementar de chamadas', ru: 'Дополнение для звонков',
    'zh-CN': '通话伴侣应用',
  },
  'Process outgoing calls': {
    en: 'Process outgoing calls', ar: 'معالجة المكالمات الصادرة',
    de: 'Ausgehende Anrufe verarbeiten', es: 'Procesar llamadas salientes',
    fr: 'Traiter les appels sortants', hi: 'आउटगोइंग कॉल प्रोसेस करें',
    id: 'Proses panggilan keluar', it: 'Elabora chiamate in uscita',
    ja: '発信通話の処理', ko: '발신 통화 처리',
    'pt-BR': 'Processar chamadas efetuadas', ru: 'Обработка исходящих вызовов',
    'zh-CN': '处理拨出电话',
  },
  'Read call log': {
    en: 'Read call log', ar: 'قراءة سجل المكالمات',
    de: 'Anrufliste lesen', es: 'Leer registro de llamadas',
    fr: 'Lire l’historique d’appels', hi: 'कॉल लॉग पढ़ें',
    id: 'Baca log panggilan', it: 'Leggi registro chiamate',
    ja: '通話履歴の読み取り', ko: '통화 기록 읽기',
    'pt-BR': 'Ler histórico de chamadas', ru: 'Чтение журнала вызовов',
    'zh-CN': '读取通话记录',
  },
  'Write call log': {
    en: 'Write call log', ar: 'كتابة سجل المكالمات',
    de: 'Anrufliste ändern', es: 'Modificar registro de llamadas',
    fr: 'Modifier l’historique d’appels', hi: 'कॉल लॉग संशोधित करें',
    id: 'Tulis log panggilan', it: 'Modifica registro chiamate',
    ja: '通話履歴の書き込み', ko: '통화 기록 쓰기',
    'pt-BR': 'Modificar histórico de chamadas', ru: 'Запись журнала вызовов',
    'zh-CN': '修改通话记录',
  },
  'VoIP calling': {
    en: 'VoIP calling', ar: 'مكالمات VoIP', de: 'VoIP-Anrufe',
    es: 'Llamadas VoIP', fr: 'Appels VoIP',
    hi: 'VoIP कॉलिंग', id: 'Panggilan VoIP', it: 'Chiamate VoIP',
    ja: 'VoIP 通話', ko: 'VoIP 통화',
    'pt-BR': 'Chamadas VoIP', ru: 'Звонки VoIP', 'zh-CN': 'VoIP 通话',
  },

  // SMS / messaging ──────────────────────────────────────────────────────────
  'Read SMS': {
    en: 'Read SMS', ar: 'قراءة الرسائل القصيرة',
    de: 'SMS lesen', es: 'Leer SMS', fr: 'Lire les SMS',
    hi: 'SMS पढ़ें', id: 'Baca SMS', it: 'Leggi SMS',
    ja: 'SMS の読み取り', ko: 'SMS 읽기',
    'pt-BR': 'Ler SMS', ru: 'Чтение SMS', 'zh-CN': '读取短信',
  },
  'Receive SMS': {
    en: 'Receive SMS', ar: 'استقبال الرسائل القصيرة',
    de: 'SMS empfangen', es: 'Recibir SMS', fr: 'Recevoir des SMS',
    hi: 'SMS प्राप्त करें', id: 'Terima SMS', it: 'Ricevi SMS',
    ja: 'SMS の受信', ko: 'SMS 수신',
    'pt-BR': 'Receber SMS', ru: 'Получение SMS', 'zh-CN': '接收短信',
  },
  'Send SMS': {
    en: 'Send SMS', ar: 'إرسال الرسائل القصيرة',
    de: 'SMS senden', es: 'Enviar SMS', fr: 'Envoyer des SMS',
    hi: 'SMS भेजें', id: 'Kirim SMS', it: 'Invia SMS',
    ja: 'SMS の送信', ko: 'SMS 전송',
    'pt-BR': 'Enviar SMS', ru: 'Отправка SMS', 'zh-CN': '发送短信',
  },
  'Modify SMS': {
    en: 'Modify SMS', ar: 'تعديل الرسائل القصيرة',
    de: 'SMS ändern', es: 'Modificar SMS', fr: 'Modifier les SMS',
    hi: 'SMS संशोधित करें', id: 'Ubah SMS', it: 'Modifica SMS',
    ja: 'SMS の変更', ko: 'SMS 수정',
    'pt-BR': 'Modificar SMS', ru: 'Изменение SMS', 'zh-CN': '修改短信',
  },
  'Receive MMS': {
    en: 'Receive MMS', ar: 'استقبال الرسائل المتعددة الوسائط',
    de: 'MMS empfangen', es: 'Recibir MMS', fr: 'Recevoir des MMS',
    hi: 'MMS प्राप्त करें', id: 'Terima MMS', it: 'Ricevi MMS',
    ja: 'MMS の受信', ko: 'MMS 수신',
    'pt-BR': 'Receber MMS', ru: 'Получение MMS', 'zh-CN': '接收彩信',
  },
  'Receive WAP push': {
    en: 'Receive WAP push', ar: 'استقبال رسائل WAP push',
    de: 'WAP-Push empfangen', es: 'Recibir WAP push',
    fr: 'Recevoir WAP push', hi: 'WAP पुश प्राप्त करें',
    id: 'Terima WAP push', it: 'Ricevi WAP push',
    ja: 'WAP プッシュの受信', ko: 'WAP 푸시 수신',
    'pt-BR': 'Receber WAP push', ru: 'Получение WAP-уведомлений',
    'zh-CN': '接收 WAP 推送',
  },
  'Read voicemail': {
    en: 'Read voicemail', ar: 'قراءة البريد الصوتي',
    de: 'Mailbox lesen', es: 'Leer buzón de voz',
    fr: 'Lire la messagerie vocale', hi: 'वॉइसमेल पढ़ें',
    id: 'Baca pesan suara', it: 'Leggi segreteria',
    ja: 'ボイスメールの読み取り', ko: '음성 메시지 읽기',
    'pt-BR': 'Ler correio de voz', ru: 'Чтение голосовой почты',
    'zh-CN': '读取语音邮件',
  },
  'Modify voicemail': {
    en: 'Modify voicemail', ar: 'تعديل البريد الصوتي',
    de: 'Mailbox ändern', es: 'Modificar buzón de voz',
    fr: 'Modifier la messagerie vocale', hi: 'वॉइसमेल संशोधित करें',
    id: 'Ubah pesan suara', it: 'Modifica segreteria',
    ja: 'ボイスメールの変更', ko: '음성 메시지 수정',
    'pt-BR': 'Modificar correio de voz', ru: 'Изменение голосовой почты',
    'zh-CN': '修改语音邮件',
  },

  // Health & fitness ─────────────────────────────────────────────────────────
  'Health (read)': {
    en: 'Health (read)', ar: 'الصحة (قراءة)', de: 'Health (lesen)',
    es: 'Salud (leer)', fr: 'Santé (lecture)',
    hi: 'स्वास्थ्य (पढ़ें)', id: 'Kesehatan (baca)', it: 'Salute (lettura)',
    ja: 'ヘルスケア (読み取り)', ko: '건강 (읽기)',
    'pt-BR': 'Saúde (leitura)', ru: 'Здоровье (чтение)',
    'zh-CN': '健康（读取）',
  },
  'Health (write)': {
    en: 'Health (write)', ar: 'الصحة (كتابة)', de: 'Health (schreiben)',
    es: 'Salud (escribir)', fr: 'Santé (écriture)',
    hi: 'स्वास्थ्य (लिखें)', id: 'Kesehatan (tulis)', it: 'Salute (scrittura)',
    ja: 'ヘルスケア (書き込み)', ko: '건강 (쓰기)',
    'pt-BR': 'Saúde (gravação)', ru: 'Здоровье (запись)',
    'zh-CN': '健康（写入）',
  },
  'Clinical health records': {
    en: 'Clinical health records', ar: 'السجلات الصحية السريرية',
    de: 'Klinische Gesundheitsdaten', es: 'Historiales clínicos',
    fr: 'Dossiers de santé cliniques', hi: 'क्लिनिकल स्वास्थ्य रिकॉर्ड',
    id: 'Rekam medis klinis', it: 'Cartelle cliniche',
    ja: '臨床医療記録', ko: '임상 건강 기록',
    'pt-BR': 'Registros clínicos de saúde', ru: 'Медицинские записи',
    'zh-CN': '临床健康记录',
  },
  'Fall detection': {
    en: 'Fall detection', ar: 'اكتشاف السقوط',
    de: 'Sturzerkennung', es: 'Detección de caídas',
    fr: 'Détection de chute', hi: 'गिरने का पता लगाना',
    id: 'Deteksi jatuh', it: 'Rilevamento cadute',
    ja: '転倒検出', ko: '낙상 감지',
    'pt-BR': 'Detecção de queda', ru: 'Обнаружение падений',
    'zh-CN': '跌倒检测',
  },
  'Motion & fitness': {
    en: 'Motion & fitness', ar: 'الحركة واللياقة',
    de: 'Bewegung & Fitness', es: 'Movimiento y forma física',
    fr: 'Mouvement et forme', hi: 'गति और फ़िटनेस',
    id: 'Gerak & kebugaran', it: 'Movimento e fitness',
    ja: 'モーションとフィットネス', ko: '동작 및 피트니스',
    'pt-BR': 'Movimento e atividade', ru: 'Движение и фитнес',
    'zh-CN': '运动与健身',
  },
  'Activity recognition': {
    en: 'Activity recognition', ar: 'التعرف على النشاط',
    de: 'Aktivitätserkennung', es: 'Reconocimiento de actividad',
    fr: 'Reconnaissance d’activité', hi: 'गतिविधि पहचान',
    id: 'Pengenalan aktivitas', it: 'Riconoscimento attività',
    ja: '身体活動の認識', ko: '활동 인식',
    'pt-BR': 'Reconhecimento de atividade', ru: 'Распознавание активности',
    'zh-CN': '活动识别',
  },

  // Voice & assistants ───────────────────────────────────────────────────────
  Siri: {
    en: 'Siri', ar: 'Siri', de: 'Siri', es: 'Siri', fr: 'Siri',
    hi: 'Siri', id: 'Siri', it: 'Siri', ja: 'Siri', ko: 'Siri',
    'pt-BR': 'Siri', ru: 'Siri', 'zh-CN': 'Siri',
  },
  'Speech recognition': {
    en: 'Speech recognition', ar: 'التعرف على الكلام',
    de: 'Spracherkennung', es: 'Reconocimiento de voz',
    fr: 'Reconnaissance vocale', hi: 'वाक् पहचान',
    id: 'Pengenalan suara', it: 'Riconoscimento vocale',
    ja: '音声認識', ko: '음성 인식',
    'pt-BR': 'Reconhecimento de fala', ru: 'Распознавание речи',
    'zh-CN': '语音识别',
  },

  // Smart home ───────────────────────────────────────────────────────────────
  HomeKit: {
    en: 'HomeKit', ar: 'HomeKit', de: 'HomeKit', es: 'HomeKit', fr: 'HomeKit',
    hi: 'HomeKit', id: 'HomeKit', it: 'HomeKit', ja: 'HomeKit', ko: 'HomeKit',
    'pt-BR': 'HomeKit', ru: 'HomeKit', 'zh-CN': 'HomeKit',
  },

  // Notifications & overlay ──────────────────────────────────────────────────
  Notifications: {
    en: 'Notifications', ar: 'الإشعارات', de: 'Benachrichtigungen',
    es: 'Notificaciones', fr: 'Notifications',
    hi: 'सूचनाएँ', id: 'Notifikasi', it: 'Notifiche',
    ja: '通知', ko: '알림',
    'pt-BR': 'Notificações', ru: 'Уведомления', 'zh-CN': '通知',
  },
  'Do Not Disturb access': {
    en: 'Do Not Disturb access', ar: 'وصول وضع عدم الإزعاج',
    de: '"Bitte nicht stören"-Zugriff', es: 'Acceso a No molestar',
    fr: 'Accès «Ne pas déranger»', hi: 'परेशान न करें ऐक्सेस',
    id: 'Akses Jangan Ganggu', it: 'Accesso a Non disturbare',
    ja: 'おやすみモードへのアクセス', ko: '방해 금지 접근',
    'pt-BR': 'Acesso ao Não perturbe', ru: 'Доступ к режиму «Не беспокоить»',
    'zh-CN': '勿扰模式访问',
  },
  'Display over apps': {
    en: 'Display over apps', ar: 'العرض فوق التطبيقات',
    de: 'Über anderen Apps anzeigen', es: 'Superponer sobre otras apps',
    fr: 'Afficher par-dessus d’autres apps',
    hi: 'अन्य ऐप्स के ऊपर प्रदर्शित करें',
    id: 'Tampil di atas aplikasi', it: 'Mostra sopra le altre app',
    ja: '他のアプリの上に表示', ko: '다른 앱 위에 표시',
    'pt-BR': 'Sobrepor outros apps', ru: 'Поверх других приложений',
    'zh-CN': '显示在其他应用上方',
  },
  'Full-screen alerts': {
    en: 'Full-screen alerts', ar: 'تنبيهات ملء الشاشة',
    de: 'Vollbild-Hinweise', es: 'Alertas a pantalla completa',
    fr: 'Alertes plein écran', hi: 'पूर्ण-स्क्रीन अलर्ट',
    id: 'Peringatan layar penuh', it: 'Avvisi a schermo intero',
    ja: '全画面アラート', ko: '전체화면 알림',
    'pt-BR': 'Alertas em tela cheia', ru: 'Полноэкранные уведомления',
    'zh-CN': '全屏提醒',
  },
  'Expand status bar': {
    en: 'Expand status bar', ar: 'توسيع شريط الحالة',
    de: 'Statusleiste erweitern', es: 'Ampliar barra de estado',
    fr: 'Déployer la barre d’état',
    hi: 'स्टेटस बार विस्तार', id: 'Perluas bilah status',
    it: 'Espandi barra di stato', ja: 'ステータスバーの展開',
    ko: '상태 바 확장', 'pt-BR': 'Expandir barra de status',
    ru: 'Развернуть строку состояния', 'zh-CN': '展开状态栏',
  },

  // Storage ──────────────────────────────────────────────────────────────────
  'Read storage': {
    en: 'Read storage', ar: 'قراءة التخزين',
    de: 'Speicher lesen', es: 'Leer almacenamiento',
    fr: 'Lire le stockage', hi: 'संग्रहण पढ़ें',
    id: 'Baca penyimpanan', it: 'Leggi archiviazione',
    ja: 'ストレージの読み取り', ko: '저장소 읽기',
    'pt-BR': 'Ler armazenamento', ru: 'Чтение хранилища',
    'zh-CN': '读取存储',
  },
  'Write storage': {
    en: 'Write storage', ar: 'كتابة التخزين',
    de: 'Speicher schreiben', es: 'Escribir en almacenamiento',
    fr: 'Écrire dans le stockage', hi: 'संग्रहण लिखें',
    id: 'Tulis penyimpanan', it: 'Scrivi archiviazione',
    ja: 'ストレージへの書き込み', ko: '저장소 쓰기',
    'pt-BR': 'Gravar armazenamento', ru: 'Запись в хранилище',
    'zh-CN': '写入存储',
  },
  'All-files access': {
    en: 'All-files access', ar: 'الوصول إلى كل الملفات',
    de: 'Vollzugriff auf alle Dateien',
    es: 'Acceso a todos los archivos',
    fr: 'Accès à tous les fichiers',
    hi: 'सभी फ़ाइलों तक पहुँच',
    id: 'Akses semua file',
    it: 'Accesso a tutti i file',
    ja: 'すべてのファイルへのアクセス',
    ko: '모든 파일 접근',
    'pt-BR': 'Acesso a todos os arquivos',
    ru: 'Доступ ко всем файлам',
    'zh-CN': '所有文件访问权限',
  },
  'Manage documents': {
    en: 'Manage documents', ar: 'إدارة المستندات',
    de: 'Dokumente verwalten', es: 'Gestionar documentos',
    fr: 'Gérer les documents', hi: 'दस्तावेज़ प्रबंधन',
    id: 'Kelola dokumen', it: 'Gestisci documenti',
    ja: 'ドキュメントの管理', ko: '문서 관리',
    'pt-BR': 'Gerenciar documentos', ru: 'Управление документами',
    'zh-CN': '管理文档',
  },
  'Clear app cache': {
    en: 'Clear app cache', ar: 'مسح ذاكرة التخزين المؤقت للتطبيق',
    de: 'App-Cache leeren', es: 'Borrar caché de la app',
    fr: 'Vider le cache de l’app', hi: 'ऐप कैश साफ़ करें',
    id: 'Hapus cache aplikasi', it: 'Svuota cache app',
    ja: 'アプリキャッシュの削除', ko: '앱 캐시 지우기',
    'pt-BR': 'Limpar cache do app', ru: 'Очистка кэша приложения',
    'zh-CN': '清除应用缓存',
  },
  'Package size': {
    en: 'Package size', ar: 'حجم الحزمة',
    de: 'Paketgröße', es: 'Tamaño del paquete',
    fr: 'Taille du paquet', hi: 'पैकेज आकार',
    id: 'Ukuran paket', it: 'Dimensione pacchetto',
    ja: 'パッケージサイズ', ko: '패키지 크기',
    'pt-BR': 'Tamanho do pacote', ru: 'Размер пакета',
    'zh-CN': '应用包大小',
  },
  'Desktop folder': {
    en: 'Desktop folder', ar: 'مجلد سطح المكتب',
    de: 'Schreibtisch-Ordner', es: 'Carpeta Escritorio',
    fr: 'Dossier Bureau', hi: 'डेस्कटॉप फ़ोल्डर',
    id: 'Folder Desktop', it: 'Cartella Scrivania',
    ja: 'デスクトップフォルダ', ko: '데스크탑 폴더',
    'pt-BR': 'Pasta Mesa', ru: 'Папка «Рабочий стол»',
    'zh-CN': '桌面文件夹',
  },
  'Documents folder': {
    en: 'Documents folder', ar: 'مجلد المستندات',
    de: 'Dokumente-Ordner', es: 'Carpeta Documentos',
    fr: 'Dossier Documents', hi: 'दस्तावेज़ फ़ोल्डर',
    id: 'Folder Dokumen', it: 'Cartella Documenti',
    ja: '書類フォルダ', ko: '문서 폴더',
    'pt-BR': 'Pasta Documentos', ru: 'Папка «Документы»',
    'zh-CN': '文稿文件夹',
  },
  'Downloads folder': {
    en: 'Downloads folder', ar: 'مجلد التنزيلات',
    de: 'Downloads-Ordner', es: 'Carpeta Descargas',
    fr: 'Dossier Téléchargements', hi: 'डाउनलोड फ़ोल्डर',
    id: 'Folder Unduhan', it: 'Cartella Download',
    ja: 'ダウンロードフォルダ', ko: '다운로드 폴더',
    'pt-BR': 'Pasta Downloads', ru: 'Папка «Загрузки»',
    'zh-CN': '下载文件夹',
  },

  // Accounts ─────────────────────────────────────────────────────────────────
  Accounts: {
    en: 'Accounts', ar: 'الحسابات', de: 'Konten', es: 'Cuentas',
    fr: 'Comptes', hi: 'खाते', id: 'Akun', it: 'Account',
    ja: 'アカウント', ko: '계정', 'pt-BR': 'Contas', ru: 'Аккаунты',
    'zh-CN': '账号',
  },
  'Manage accounts': {
    en: 'Manage accounts', ar: 'إدارة الحسابات',
    de: 'Konten verwalten', es: 'Gestionar cuentas',
    fr: 'Gérer les comptes', hi: 'खाते प्रबंधित करें',
    id: 'Kelola akun', it: 'Gestisci account',
    ja: 'アカウントの管理', ko: '계정 관리',
    'pt-BR': 'Gerenciar contas', ru: 'Управление аккаунтами',
    'zh-CN': '管理账号',
  },
  'Authenticate accounts': {
    en: 'Authenticate accounts', ar: 'مصادقة الحسابات',
    de: 'Konten authentifizieren', es: 'Autenticar cuentas',
    fr: 'Authentifier les comptes', hi: 'खाते प्रमाणित करें',
    id: 'Autentikasi akun', it: 'Autentica account',
    ja: 'アカウントの認証', ko: '계정 인증',
    'pt-BR': 'Autenticar contas', ru: 'Аутентификация аккаунтов',
    'zh-CN': '验证账号',
  },
  'Read sync settings': {
    en: 'Read sync settings', ar: 'قراءة إعدادات المزامنة',
    de: 'Synchronisierungseinstellungen lesen',
    es: 'Leer ajustes de sincronización',
    fr: 'Lire les paramètres de synchronisation',
    hi: 'सिंक सेटिंग पढ़ें',
    id: 'Baca pengaturan sinkronisasi',
    it: 'Leggi impostazioni di sincronizzazione',
    ja: '同期設定の読み取り',
    ko: '동기화 설정 읽기',
    'pt-BR': 'Ler config. de sincronização',
    ru: 'Чтение настроек синхронизации',
    'zh-CN': '读取同步设置',
  },
  'Read sync stats': {
    en: 'Read sync stats', ar: 'قراءة إحصائيات المزامنة',
    de: 'Synchronisierungsstatistiken lesen',
    es: 'Leer estadísticas de sincronización',
    fr: 'Lire les statistiques de synchronisation',
    hi: 'सिंक आँकड़े पढ़ें',
    id: 'Baca statistik sinkronisasi',
    it: 'Leggi statistiche sincronizzazione',
    ja: '同期統計の読み取り',
    ko: '동기화 통계 읽기',
    'pt-BR': 'Ler estatísticas de sincronização',
    ru: 'Чтение статистики синхронизации',
    'zh-CN': '读取同步统计',
  },
  'Modify sync settings': {
    en: 'Modify sync settings', ar: 'تعديل إعدادات المزامنة',
    de: 'Synchronisierung ändern', es: 'Modificar sincronización',
    fr: 'Modifier la synchronisation', hi: 'सिंक सेटिंग बदलें',
    id: 'Ubah pengaturan sinkronisasi', it: 'Modifica sincronizzazione',
    ja: '同期設定の変更', ko: '동기화 설정 변경',
    'pt-BR': 'Alterar config. de sincronização', ru: 'Изменение синхронизации',
    'zh-CN': '修改同步设置',
  },
  'Read profile': {
    en: 'Read profile', ar: 'قراءة الملف الشخصي',
    de: 'Profil lesen', es: 'Leer perfil',
    fr: 'Lire le profil', hi: 'प्रोफ़ाइल पढ़ें',
    id: 'Baca profil', it: 'Leggi profilo',
    ja: 'プロフィールの読み取り', ko: '프로필 읽기',
    'pt-BR': 'Ler perfil', ru: 'Чтение профиля', 'zh-CN': '读取个人资料',
  },
  'Write profile': {
    en: 'Write profile', ar: 'كتابة الملف الشخصي',
    de: 'Profil schreiben', es: 'Modificar perfil',
    fr: 'Modifier le profil', hi: 'प्रोफ़ाइल संशोधित करें',
    id: 'Tulis profil', it: 'Modifica profilo',
    ja: 'プロフィールの書き込み', ko: '프로필 쓰기',
    'pt-BR': 'Modificar perfil', ru: 'Запись профиля',
    'zh-CN': '修改个人资料',
  },
  'Game Center friends': {
    en: 'Game Center friends', ar: 'أصدقاء Game Center',
    de: 'Game-Center-Freunde', es: 'Amigos de Game Center',
    fr: 'Amis Game Center', hi: 'Game Center मित्र',
    id: 'Teman Game Center', it: 'Amici Game Center',
    ja: 'Game Center の友達', ko: 'Game Center 친구',
    'pt-BR': 'Amigos do Game Center', ru: 'Друзья Game Center',
    'zh-CN': 'Game Center 好友',
  },

  // Foreground services (Android) ────────────────────────────────────────────
  'Foreground service': {
    en: 'Foreground service', ar: 'خدمة في المقدمة',
    de: 'Vordergrunddienst', es: 'Servicio en primer plano',
    fr: 'Service au premier plan', hi: 'फ़ोरग्राउंड सेवा',
    id: 'Layanan latar depan', it: 'Servizio in primo piano',
    ja: 'フォアグラウンドサービス', ko: '포그라운드 서비스',
    'pt-BR': 'Serviço em primeiro plano', ru: 'Служба на переднем плане',
    'zh-CN': '前台服务',
  },
  'Foreground camera': {
    en: 'Foreground camera', ar: 'الكاميرا في المقدمة',
    de: 'Kamera im Vordergrund', es: 'Cámara en primer plano',
    fr: 'Caméra au premier plan', hi: 'फ़ोरग्राउंड कैमरा',
    id: 'Kamera latar depan', it: 'Fotocamera in primo piano',
    ja: 'フォアグラウンドのカメラ', ko: '포그라운드 카메라',
    'pt-BR': 'Câmera em primeiro plano', ru: 'Камера на переднем плане',
    'zh-CN': '前台相机',
  },
  'Foreground microphone': {
    en: 'Foreground microphone', ar: 'الميكروفون في المقدمة',
    de: 'Mikrofon im Vordergrund', es: 'Micrófono en primer plano',
    fr: 'Microphone au premier plan', hi: 'फ़ोरग्राउंड माइक्रोफ़ोन',
    id: 'Mikrofon latar depan', it: 'Microfono in primo piano',
    ja: 'フォアグラウンドのマイク', ko: '포그라운드 마이크',
    'pt-BR': 'Microfone em primeiro plano', ru: 'Микрофон на переднем плане',
    'zh-CN': '前台麦克风',
  },
  'Foreground location': {
    en: 'Foreground location', ar: 'الموقع في المقدمة',
    de: 'Standort im Vordergrund', es: 'Ubicación en primer plano',
    fr: 'Position au premier plan', hi: 'फ़ोरग्राउंड स्थान',
    id: 'Lokasi latar depan', it: 'Posizione in primo piano',
    ja: 'フォアグラウンドの位置情報', ko: '포그라운드 위치',
    'pt-BR': 'Localização em primeiro plano', ru: 'Местоположение на переднем плане',
    'zh-CN': '前台位置',
  },
  'Foreground health': {
    en: 'Foreground health', ar: 'الصحة في المقدمة',
    de: 'Gesundheit im Vordergrund', es: 'Salud en primer plano',
    fr: 'Santé au premier plan', hi: 'फ़ोरग्राउंड स्वास्थ्य',
    id: 'Kesehatan latar depan', it: 'Salute in primo piano',
    ja: 'フォアグラウンドの健康データ', ko: '포그라운드 건강',
    'pt-BR': 'Saúde em primeiro plano', ru: 'Здоровье на переднем плане',
    'zh-CN': '前台健康',
  },
  'Foreground data sync': {
    en: 'Foreground data sync', ar: 'مزامنة البيانات في المقدمة',
    de: 'Datensynchronisierung im Vordergrund',
    es: 'Sincronización en primer plano',
    fr: 'Synchronisation au premier plan',
    hi: 'फ़ोरग्राउंड डेटा सिंक',
    id: 'Sinkronisasi data latar depan',
    it: 'Sincronizzazione in primo piano',
    ja: 'フォアグラウンドのデータ同期',
    ko: '포그라운드 데이터 동기화',
    'pt-BR': 'Sincronização em primeiro plano',
    ru: 'Синхронизация на переднем плане',
    'zh-CN': '前台数据同步',
  },
  'Foreground media playback': {
    en: 'Foreground media playback', ar: 'تشغيل الوسائط في المقدمة',
    de: 'Medienwiedergabe im Vordergrund', es: 'Reproducción en primer plano',
    fr: 'Lecture média au premier plan', hi: 'फ़ोरग्राउंड मीडिया प्लेबैक',
    id: 'Pemutaran media latar depan', it: 'Riproduzione media in primo piano',
    ja: 'フォアグラウンドのメディア再生', ko: '포그라운드 미디어 재생',
    'pt-BR': 'Reprodução em primeiro plano', ru: 'Воспроизведение на переднем плане',
    'zh-CN': '前台媒体播放',
  },
  'Foreground media processing': {
    en: 'Foreground media processing', ar: 'معالجة الوسائط في المقدمة',
    de: 'Medienverarbeitung im Vordergrund', es: 'Proceso media en primer plano',
    fr: 'Traitement média au premier plan', hi: 'फ़ोरग्राउंड मीडिया प्रोसेसिंग',
    id: 'Pemrosesan media latar depan', it: 'Elaborazione media in primo piano',
    ja: 'フォアグラウンドのメディア処理', ko: '포그라운드 미디어 처리',
    'pt-BR': 'Processamento em primeiro plano', ru: 'Обработка медиа на переднем плане',
    'zh-CN': '前台媒体处理',
  },
  'Foreground screen capture': {
    en: 'Foreground screen capture', ar: 'التقاط الشاشة في المقدمة',
    de: 'Bildschirmaufnahme im Vordergrund',
    es: 'Captura de pantalla en primer plano',
    fr: 'Capture d’écran au premier plan',
    hi: 'फ़ोरग्राउंड स्क्रीन कैप्चर',
    id: 'Tangkapan layar latar depan',
    it: 'Cattura schermo in primo piano',
    ja: 'フォアグラウンドの画面キャプチャ',
    ko: '포그라운드 화면 캡처',
    'pt-BR': 'Captura de tela em primeiro plano',
    ru: 'Захват экрана на переднем плане',
    'zh-CN': '前台屏幕捕获',
  },
  'Foreground messaging': {
    en: 'Foreground messaging', ar: 'المراسلة في المقدمة',
    de: 'Nachrichtenversand im Vordergrund',
    es: 'Mensajería en primer plano',
    fr: 'Messagerie au premier plan',
    hi: 'फ़ोरग्राउंड संदेश',
    id: 'Pesan latar depan',
    it: 'Messaggistica in primo piano',
    ja: 'フォアグラウンドのメッセージング',
    ko: '포그라운드 메시지',
    'pt-BR': 'Mensagens em primeiro plano',
    ru: 'Сообщения на переднем плане',
    'zh-CN': '前台消息',
  },
  'Foreground phone call': {
    en: 'Foreground phone call', ar: 'مكالمة هاتفية في المقدمة',
    de: 'Telefonanruf im Vordergrund',
    es: 'Llamada en primer plano',
    fr: 'Appel téléphonique au premier plan',
    hi: 'फ़ोरग्राउंड फ़ोन कॉल',
    id: 'Panggilan latar depan',
    it: 'Chiamata in primo piano',
    ja: 'フォアグラウンドの通話',
    ko: '포그라운드 통화',
    'pt-BR': 'Chamada em primeiro plano',
    ru: 'Звонок на переднем плане',
    'zh-CN': '前台通话',
  },
  'Foreground connected device': {
    en: 'Foreground connected device', ar: 'الجهاز المتصل في المقدمة',
    de: 'Verbundenes Gerät im Vordergrund',
    es: 'Dispositivo conectado en primer plano',
    fr: 'Appareil connecté au premier plan',
    hi: 'फ़ोरग्राउंड कनेक्टेड डिवाइस',
    id: 'Perangkat terhubung latar depan',
    it: 'Dispositivo connesso in primo piano',
    ja: 'フォアグラウンドの接続機器',
    ko: '포그라운드 연결 기기',
    'pt-BR': 'Dispositivo conectado em primeiro plano',
    ru: 'Подключённое устройство на переднем плане',
    'zh-CN': '前台已连接设备',
  },
  'Foreground (special use)': {
    en: 'Foreground (special use)', ar: 'في المقدمة (استخدام خاص)',
    de: 'Vordergrund (Sonderzweck)', es: 'Primer plano (uso especial)',
    fr: 'Premier plan (usage spécial)', hi: 'फ़ोरग्राउंड (विशेष उपयोग)',
    id: 'Latar depan (penggunaan khusus)', it: 'Primo piano (uso speciale)',
    ja: 'フォアグラウンド (特殊用途)', ko: '포그라운드 (특수 용도)',
    'pt-BR': 'Primeiro plano (uso especial)', ru: 'Передний план (особое назначение)',
    'zh-CN': '前台（特殊用途）',
  },
  'Foreground (system-exempt)': {
    en: 'Foreground (system-exempt)', ar: 'في المقدمة (مستثنى من النظام)',
    de: 'Vordergrund (systembefreit)',
    es: 'Primer plano (exento del sistema)',
    fr: 'Premier plan (exempté système)',
    hi: 'फ़ोरग्राउंड (सिस्टम-मुक्त)',
    id: 'Latar depan (dikecualikan sistem)',
    it: 'Primo piano (esente dal sistema)',
    ja: 'フォアグラウンド (システム例外)',
    ko: '포그라운드 (시스템 면제)',
    'pt-BR': 'Primeiro plano (isento pelo sistema)',
    ru: 'Передний план (системное исключение)',
    'zh-CN': '前台（系统豁免）',
  },

  // Apps & system ────────────────────────────────────────────────────────────
  'Install apps': {
    en: 'Install apps', ar: 'تثبيت التطبيقات',
    de: 'Apps installieren', es: 'Instalar apps',
    fr: 'Installer des apps', hi: 'ऐप्स इंस्टॉल करें',
    id: 'Pasang aplikasi', it: 'Installa app',
    ja: 'アプリのインストール', ko: '앱 설치',
    'pt-BR': 'Instalar apps', ru: 'Установка приложений',
    'zh-CN': '安装应用',
  },
  'Request app removal': {
    en: 'Request app removal', ar: 'طلب إزالة التطبيقات',
    de: 'App-Deinstallation anfragen', es: 'Solicitar eliminar apps',
    fr: 'Demander la suppression d’app', hi: 'ऐप हटाने का अनुरोध',
    id: 'Minta pencopotan aplikasi', it: 'Richiedi rimozione app',
    ja: 'アプリの削除を要求', ko: '앱 제거 요청',
    'pt-BR': 'Solicitar remoção de apps', ru: 'Запрос на удаление приложения',
    'zh-CN': '请求删除应用',
  },
  'Query installed apps': {
    en: 'Query installed apps', ar: 'الاستعلام عن التطبيقات المثبتة',
    de: 'Installierte Apps abfragen', es: 'Consultar apps instaladas',
    fr: 'Interroger les apps installées', hi: 'इंस्टॉल किए गए ऐप्स की क्वेरी',
    id: 'Kueri aplikasi terpasang', it: 'Interroga app installate',
    ja: 'インストール済みアプリの照会', ko: '설치된 앱 조회',
    'pt-BR': 'Consultar apps instalados', ru: 'Запрос установленных приложений',
    'zh-CN': '查询已安装应用',
  },
  'Kill background apps': {
    en: 'Kill background apps', ar: 'إيقاف التطبيقات في الخلفية',
    de: 'Hintergrund-Apps beenden', es: 'Cerrar apps en segundo plano',
    fr: 'Fermer les apps en arrière-plan', hi: 'पृष्ठभूमि ऐप्स बंद करें',
    id: 'Hentikan aplikasi latar belakang', it: 'Chiudi app in background',
    ja: 'バックグラウンドアプリの停止', ko: '백그라운드 앱 종료',
    'pt-BR': 'Encerrar apps em segundo plano', ru: 'Остановка фоновых приложений',
    'zh-CN': '终止后台应用',
  },
  'Reorder tasks': {
    en: 'Reorder tasks', ar: 'إعادة ترتيب المهام',
    de: 'Aufgaben neu ordnen', es: 'Reordenar tareas',
    fr: 'Réorganiser les tâches', hi: 'कार्य पुनः क्रमित करें',
    id: 'Atur ulang tugas', it: 'Riordina attività',
    ja: 'タスクの並べ替え', ko: '작업 재정렬',
    'pt-BR': 'Reordenar tarefas', ru: 'Изменение порядка задач',
    'zh-CN': '重新排序任务',
  },
  'Run at startup': {
    en: 'Run at startup', ar: 'التشغيل عند بدء التشغيل',
    de: 'Beim Start ausführen', es: 'Ejecutar al inicio',
    fr: 'Lancer au démarrage', hi: 'स्टार्टअप पर चलाएँ',
    id: 'Jalankan saat startup', it: 'Avvia all’accensione',
    ja: '起動時に実行', ko: '부팅 시 실행',
    'pt-BR': 'Executar na inicialização', ru: 'Запуск при старте',
    'zh-CN': '开机时运行',
  },
  'Stay awake': {
    en: 'Stay awake', ar: 'البقاء مستيقظاً',
    de: 'Wachhalten', es: 'Mantener activo',
    fr: 'Rester actif', hi: 'जागृत रखें',
    id: 'Tetap aktif', it: 'Resta attivo',
    ja: 'スリープ防止', ko: '깨어 있기',
    'pt-BR': 'Manter ativo', ru: 'Не уходить в сон',
    'zh-CN': '保持唤醒',
  },
  'App usage stats': {
    en: 'App usage stats', ar: 'إحصاءات استخدام التطبيقات',
    de: 'App-Nutzungsstatistik', es: 'Estadísticas de uso de apps',
    fr: 'Statistiques d’utilisation', hi: 'ऐप उपयोग आँकड़े',
    id: 'Statistik penggunaan aplikasi', it: 'Statistiche di utilizzo app',
    ja: 'アプリ使用状況', ko: '앱 사용 통계',
    'pt-BR': 'Uso de aplicativos', ru: 'Статистика использования приложений',
    'zh-CN': '应用使用统计',
  },
  'Read app badges': {
    en: 'Read app badges', ar: 'قراءة شارات التطبيق',
    de: 'App-Symbol-Badges lesen', es: 'Leer insignias de apps',
    fr: 'Lire les badges d’app', hi: 'ऐप बैज पढ़ें',
    id: 'Baca lencana aplikasi', it: 'Leggi badge app',
    ja: 'アプリのバッジ読み取り', ko: '앱 배지 읽기',
    'pt-BR': 'Ler emblemas de apps', ru: 'Чтение значков приложений',
    'zh-CN': '读取应用角标',
  },
  'Create shortcuts': {
    en: 'Create shortcuts', ar: 'إنشاء اختصارات',
    de: 'Verknüpfungen erstellen', es: 'Crear accesos directos',
    fr: 'Créer des raccourcis', hi: 'शॉर्टकट बनाएँ',
    id: 'Buat pintasan', it: 'Crea scorciatoie',
    ja: 'ショートカットの作成', ko: '바로가기 만들기',
    'pt-BR': 'Criar atalhos', ru: 'Создание ярлыков', 'zh-CN': '创建快捷方式',
  },
  'Audio settings': {
    en: 'Audio settings', ar: 'إعدادات الصوت',
    de: 'Audioeinstellungen', es: 'Ajustes de audio',
    fr: 'Réglages audio', hi: 'ऑडियो सेटिंग',
    id: 'Pengaturan audio', it: 'Impostazioni audio',
    ja: '音声設定', ko: '오디오 설정',
    'pt-BR': 'Configurações de áudio', ru: 'Настройки звука',
    'zh-CN': '音频设置',
  },
  'Modify settings': {
    en: 'Modify settings', ar: 'تعديل الإعدادات',
    de: 'Einstellungen ändern', es: 'Modificar ajustes',
    fr: 'Modifier les réglages', hi: 'सेटिंग संशोधित करें',
    id: 'Ubah pengaturan', it: 'Modifica impostazioni',
    ja: '設定の変更', ko: '설정 변경',
    'pt-BR': 'Modificar configurações', ru: 'Изменение настроек',
    'zh-CN': '修改设置',
  },
  'Set wallpaper': {
    en: 'Set wallpaper', ar: 'تعيين الخلفية',
    de: 'Hintergrund festlegen', es: 'Establecer fondo de pantalla',
    fr: 'Définir le fond d’écran', hi: 'वॉलपेपर सेट करें',
    id: 'Atur wallpaper', it: 'Imposta sfondo',
    ja: '壁紙の設定', ko: '배경화면 설정',
    'pt-BR': 'Definir papel de parede', ru: 'Установка обоев',
    'zh-CN': '设置壁纸',
  },
  'Set time zone': {
    en: 'Set time zone', ar: 'ضبط المنطقة الزمنية',
    de: 'Zeitzone festlegen', es: 'Establecer zona horaria',
    fr: 'Définir le fuseau horaire', hi: 'टाइम ज़ोन सेट करें',
    id: 'Atur zona waktu', it: 'Imposta fuso orario',
    ja: 'タイムゾーンの設定', ko: '시간대 설정',
    'pt-BR': 'Definir fuso horário', ru: 'Установка часового пояса',
    'zh-CN': '设置时区',
  },
  'Set alarm': {
    en: 'Set alarm', ar: 'ضبط المنبه',
    de: 'Wecker stellen', es: 'Programar alarma',
    fr: 'Régler une alarme', hi: 'अलार्म सेट करें',
    id: 'Atur alarm', it: 'Imposta sveglia',
    ja: 'アラームの設定', ko: '알람 설정',
    'pt-BR': 'Definir alarme', ru: 'Установка будильника',
    'zh-CN': '设置闹钟',
  },
  'Exact alarm': {
    en: 'Exact alarm', ar: 'منبه دقيق',
    de: 'Exakter Wecker', es: 'Alarma exacta',
    fr: 'Alarme précise', hi: 'सटीक अलार्म',
    id: 'Alarm tepat waktu', it: 'Sveglia precisa',
    ja: '正確なアラーム', ko: '정확한 알람',
    'pt-BR': 'Alarme exato', ru: 'Точный будильник',
    'zh-CN': '精确闹钟',
  },
  'Exact alarms': {
    en: 'Exact alarms', ar: 'منبهات دقيقة',
    de: 'Exakte Wecker', es: 'Alarmas exactas',
    fr: 'Alarmes précises', hi: 'सटीक अलार्म',
    id: 'Alarm tepat waktu', it: 'Sveglie precise',
    ja: '正確なアラーム', ko: '정확한 알람',
    'pt-BR': 'Alarmes exatos', ru: 'Точные будильники',
    'zh-CN': '精确闹钟',
  },

  // Tracking & screen capture ────────────────────────────────────────────────
  Tracking: {
    en: 'Tracking', ar: 'التتبع', de: 'Tracking',
    es: 'Seguimiento', fr: 'Suivi',
    hi: 'ट्रैकिंग', id: 'Pelacakan', it: 'Tracciamento',
    ja: 'トラッキング', ko: '추적',
    'pt-BR': 'Rastreamento', ru: 'Отслеживание', 'zh-CN': '跟踪',
  },
  'Screenshot detection': {
    en: 'Screenshot detection', ar: 'اكتشاف لقطة الشاشة',
    de: 'Screenshot-Erkennung', es: 'Detección de capturas',
    fr: 'Détection de captures d’écran', hi: 'स्क्रीनशॉट पहचान',
    id: 'Deteksi tangkapan layar', it: 'Rilevamento screenshot',
    ja: 'スクリーンショットの検出', ko: '스크린샷 감지',
    'pt-BR': 'Detecção de captura de tela', ru: 'Обнаружение скриншотов',
    'zh-CN': '截屏检测',
  },
  'Screen-recording detection': {
    en: 'Screen-recording detection', ar: 'اكتشاف تسجيل الشاشة',
    de: 'Bildschirmaufnahme-Erkennung', es: 'Detección de grabación',
    fr: 'Détection d’enregistrement d’écran', hi: 'स्क्रीन-रिकॉर्डिंग पहचान',
    id: 'Deteksi perekaman layar', it: 'Rilevamento registrazione schermo',
    ja: '画面録画の検出', ko: '화면 녹화 감지',
    'pt-BR': 'Detecção de gravação de tela', ru: 'Обнаружение записи экрана',
    'zh-CN': '录屏检测',
  },

  // iOS-specific & misc ──────────────────────────────────────────────────────
  'Control other apps': {
    en: 'Control other apps', ar: 'التحكم في التطبيقات الأخرى',
    de: 'Andere Apps steuern', es: 'Controlar otras apps',
    fr: 'Contrôler d’autres apps', hi: 'अन्य ऐप्स को नियंत्रित करें',
    id: 'Mengontrol aplikasi lain', it: 'Controlla altre app',
    ja: '他のアプリの制御', ko: '다른 앱 제어',
    'pt-BR': 'Controlar outros apps', ru: 'Управление другими приложениями',
    'zh-CN': '控制其他应用',
  },
  'Focus status': {
    en: 'Focus status', ar: 'حالة التركيز',
    de: 'Fokusstatus', es: 'Estado de Concentración',
    fr: 'État du Focus', hi: 'फ़ोकस स्थिति',
    id: 'Status Fokus', it: 'Stato Full Immersion',
    ja: '集中モードの状態', ko: '집중 모드 상태',
    'pt-BR': 'Estado do Foco', ru: 'Статус «Фокусирование»',
    'zh-CN': '专注状态',
  },
  'Financial data': {
    en: 'Financial data', ar: 'البيانات المالية',
    de: 'Finanzdaten', es: 'Datos financieros',
    fr: 'Données financières', hi: 'वित्तीय डेटा',
    id: 'Data keuangan', it: 'Dati finanziari',
    ja: '金融データ', ko: '금융 데이터',
    'pt-BR': 'Dados financeiros', ru: 'Финансовые данные',
    'zh-CN': '财务数据',
  },
  'TV subscription account': {
    en: 'TV subscription account', ar: 'حساب اشتراك التلفاز',
    de: 'TV-Abonnement-Konto', es: 'Cuenta de suscripción de TV',
    fr: 'Compte d’abonnement TV', hi: 'टीवी सदस्यता खाता',
    id: 'Akun langganan TV', it: 'Account abbonamento TV',
    ja: 'TV サブスクリプション アカウント', ko: 'TV 구독 계정',
    'pt-BR': 'Conta de assinatura de TV', ru: 'Учётная запись ТВ-подписки',
    'zh-CN': '电视订阅账号',
  },
  'World sensing': {
    en: 'World sensing', ar: 'استشعار البيئة المحيطة',
    de: 'Weltwahrnehmung', es: 'Detección del entorno',
    fr: 'Perception du monde', hi: 'विश्व-संवेदन',
    id: 'Penginderaan dunia', it: 'Rilevamento ambientale',
    ja: 'ワールドセンシング', ko: '월드 센싱',
    'pt-BR': 'Detecção do ambiente', ru: 'Восприятие окружения',
    'zh-CN': '环境感知',
  },
  'System administration': {
    en: 'System administration', ar: 'إدارة النظام',
    de: 'Systemverwaltung', es: 'Administración del sistema',
    fr: 'Administration système', hi: 'सिस्टम प्रशासन',
    id: 'Administrasi sistem', it: 'Amministrazione di sistema',
    ja: 'システム管理', ko: '시스템 관리',
    'pt-BR': 'Administração do sistema', ru: 'Администрирование системы',
    'zh-CN': '系统管理',
  },
  'System extension': {
    en: 'System extension', ar: 'امتداد النظام',
    de: 'Systemerweiterung', es: 'Extensión del sistema',
    fr: 'Extension système', hi: 'सिस्टम एक्सटेंशन',
    id: 'Ekstensi sistem', it: 'Estensione di sistema',
    ja: 'システム拡張', ko: '시스템 확장',
    'pt-BR': 'Extensão do sistema', ru: 'Системное расширение',
    'zh-CN': '系统扩展',
  },
};

/** Look up a localized permission display name. */
export function lookupPermissionLabel(englishLabel: string, locale: string): string {
  const table = PERMISSION_LABELS[englishLabel];
  if (!table) return englishLabel;
  if (locale in table) return table[locale]!;
  const lang = languageOnly(locale);
  if (lang in table) return table[lang]!;
  for (const k of Object.keys(table)) {
    if (languageOnly(k) === lang) return table[k]!;
  }
  if ('en' in table) return table['en']!;
  const first = Object.keys(table)[0];
  return first ? table[first]! : englishLabel;
}

// -----------------------------------------------------------------------------
// Android permission descriptions
// -----------------------------------------------------------------------------

export const ANDROID_PERMISSION_DESCRIPTIONS: Record<string, LocalizedString> = {
  ACCEPT_HANDOVER: {
    en: 'Continues a phone call started in another app.',
    ar: 'يكمل المكالمة الهاتفية التي بدأت في تطبيق آخر.',
    de: 'Setzt einen in einer anderen App begonnenen Anruf fort.',
    es: 'Continúa una llamada iniciada en otra aplicación.',
    fr: 'Poursuit un appel commencé dans une autre application.',
    hi: 'किसी अन्य ऐप में शुरू की गई कॉल को जारी रखता है।',
    id: 'Melanjutkan panggilan yang dimulai di aplikasi lain.',
    it: 'Continua una chiamata iniziata in un’altra app.',
    ja: '他のアプリで始まった通話を引き継ぎます。',
    ko: '다른 앱에서 시작된 통화를 이어받습니다.',
    'pt-BR': 'Continua uma chamada iniciada em outro app.',
    ru: 'Продолжает звонок, начатый в другом приложении.',
    'zh-CN': '接续在其他应用中发起的通话。',
  },
  ACCESS_BACKGROUND_LOCATION: {
    en: 'Accesses your location while the app is in the background.',
    ar: 'يصل إلى موقعك أثناء عمل التطبيق في الخلفية.',
    de: 'Greift im Hintergrund auf deinen Standort zu.',
    es: 'Accede a tu ubicación cuando la aplicación está en segundo plano.',
    fr: 'Accède à votre position quand l’app est en arrière-plan.',
    hi: 'जब ऐप पृष्ठभूमि में हो, तब आपके स्थान तक पहुँचता है।',
    id: 'Mengakses lokasi Anda saat aplikasi berjalan di latar belakang.',
    it: 'Accede alla tua posizione quando l’app è in background.',
    ja: 'アプリがバックグラウンドにあるときも位置情報にアクセスします。',
    ko: '앱이 백그라운드에 있을 때도 위치를 확인합니다.',
    'pt-BR': 'Acessa sua localização enquanto o app está em segundo plano.',
    ru: 'Получает доступ к вашему местоположению в фоновом режиме.',
    'zh-CN': '在应用处于后台时访问您的位置。',
  },
  ACCESS_COARSE_LOCATION: {
    en: 'Accesses your approximate location.',
    ar: 'يصل إلى موقعك التقريبي.',
    de: 'Greift auf deinen ungefähren Standort zu.',
    es: 'Accede a tu ubicación aproximada.',
    fr: 'Accède à votre position approximative.',
    hi: 'आपके अनुमानित स्थान तक पहुँचता है।',
    id: 'Mengakses perkiraan lokasi Anda.',
    it: 'Accede alla tua posizione approssimativa.',
    ja: 'おおよその位置情報にアクセスします。',
    ko: '대략적인 위치를 확인합니다.',
    'pt-BR': 'Acessa sua localização aproximada.',
    ru: 'Получает доступ к приблизительному местоположению.',
    'zh-CN': '获取您的大致位置。',
  },
  ACCESS_FINE_LOCATION: {
    en: 'Accesses your precise location.',
    ar: 'يصل إلى موقعك الدقيق.',
    de: 'Greift auf deinen genauen Standort zu.',
    es: 'Accede a tu ubicación precisa.',
    fr: 'Accède à votre position précise.',
    hi: 'आपके सटीक स्थान तक पहुँचता है।',
    id: 'Mengakses lokasi tepat Anda.',
    it: 'Accede alla tua posizione precisa.',
    ja: '正確な位置情報にアクセスします。',
    ko: '정확한 위치를 확인합니다.',
    'pt-BR': 'Acessa sua localização precisa.',
    ru: 'Получает доступ к точному местоположению.',
    'zh-CN': '获取您的精确位置。',
  },
  ACCESS_NETWORK_STATE: {
    en: 'Reads information about the device’s network connections.',
    ar: 'يقرأ معلومات عن اتصالات شبكة الجهاز.',
    de: 'Liest Informationen über die Netzwerkverbindungen des Geräts.',
    es: 'Lee información sobre las conexiones de red del dispositivo.',
    fr: 'Lit les informations sur les connexions réseau de l’appareil.',
    hi: 'डिवाइस के नेटवर्क कनेक्शन की जानकारी पढ़ता है।',
    id: 'Membaca informasi koneksi jaringan perangkat.',
    it: 'Legge informazioni sulle connessioni di rete del dispositivo.',
    ja: '端末のネットワーク接続情報を読み取ります。',
    ko: '기기의 네트워크 연결 정보를 읽습니다.',
    'pt-BR': 'Lê informações sobre as conexões de rede do dispositivo.',
    ru: 'Считывает сведения о сетевых подключениях устройства.',
    'zh-CN': '读取设备的网络连接信息。',
  },
  ACCESS_WIFI_STATE: {
    en: 'Reads information about Wi-Fi networks.',
    ar: 'يقرأ معلومات عن شبكات Wi-Fi.',
    de: 'Liest Informationen über WLAN-Netzwerke.',
    es: 'Lee información sobre las redes Wi-Fi.',
    fr: 'Lit les informations sur les réseaux Wi-Fi.',
    hi: 'वाई-फ़ाई नेटवर्क की जानकारी पढ़ता है।',
    id: 'Membaca informasi tentang jaringan Wi-Fi.',
    it: 'Legge informazioni sulle reti Wi-Fi.',
    ja: 'Wi-Fi ネットワークの情報を読み取ります。',
    ko: 'Wi-Fi 네트워크 정보를 읽습니다.',
    'pt-BR': 'Lê informações sobre redes Wi-Fi.',
    ru: 'Считывает сведения о сетях Wi-Fi.',
    'zh-CN': '读取 Wi-Fi 网络的信息。',
  },
  ACTIVITY_RECOGNITION: {
    en: 'Detects your physical activity, such as walking or running.',
    ar: 'يكتشف نشاطك البدني، مثل المشي أو الجري.',
    de: 'Erkennt körperliche Aktivitäten wie Gehen oder Laufen.',
    es: 'Detecta tu actividad física, como caminar o correr.',
    fr: 'Détecte votre activité physique, comme la marche ou la course.',
    hi: 'आपकी शारीरिक गतिविधि जैसे चलना या दौड़ना पहचानता है।',
    id: 'Mendeteksi aktivitas fisik Anda, seperti berjalan atau berlari.',
    it: 'Rileva la tua attività fisica, come camminare o correre.',
    ja: '歩行や走行などの身体活動を検知します。',
    ko: '걷기, 달리기 등의 신체 활동을 감지합니다.',
    'pt-BR': 'Detecta sua atividade física, como caminhar ou correr.',
    ru: 'Распознаёт вашу физическую активность, например ходьбу или бег.',
    'zh-CN': '识别走路、跑步等身体活动。',
  },
  ANSWER_PHONE_CALLS: {
    en: 'Answers incoming phone calls.',
    ar: 'يجيب على المكالمات الواردة.',
    de: 'Beantwortet eingehende Anrufe.',
    es: 'Contesta llamadas entrantes.',
    fr: 'Répond aux appels entrants.',
    hi: 'आने वाली कॉलों का उत्तर देता है।',
    id: 'Menjawab panggilan masuk.',
    it: 'Risponde alle chiamate in arrivo.',
    ja: '着信に応答します。',
    ko: '수신 전화에 응답합니다.',
    'pt-BR': 'Atende chamadas recebidas.',
    ru: 'Отвечает на входящие звонки.',
    'zh-CN': '接听来电。',
  },
  AUTHENTICATE_ACCOUNTS: {
    en: 'Acts as an authenticator for accounts on the device.',
    ar: 'يعمل كمصدر مصادقة للحسابات على الجهاز.',
    de: 'Fungiert als Authentifikator für Konten auf dem Gerät.',
    es: 'Actúa como autenticador de cuentas del dispositivo.',
    fr: 'Sert d’authentificateur pour les comptes de l’appareil.',
    hi: 'डिवाइस के खातों के लिए प्रमाणीकरणकर्ता के रूप में कार्य करता है।',
    id: 'Berperan sebagai autentikator untuk akun di perangkat.',
    it: 'Funge da autenticatore per gli account sul dispositivo.',
    ja: '端末のアカウントの認証元として動作します。',
    ko: '기기의 계정 인증 제공자로 동작합니다.',
    'pt-BR': 'Atua como autenticador para contas no dispositivo.',
    ru: 'Выступает как аутентификатор для учётных записей на устройстве.',
    'zh-CN': '为设备上的账号提供身份验证。',
  },
  BLUETOOTH: {
    en: 'Connects to paired Bluetooth devices.',
    ar: 'يتصل بأجهزة البلوتوث المقترنة.',
    de: 'Verbindet sich mit gekoppelten Bluetooth-Geräten.',
    es: 'Se conecta a dispositivos Bluetooth emparejados.',
    fr: 'Se connecte aux appareils Bluetooth jumelés.',
    hi: 'जोड़े गए ब्लूटूथ डिवाइसों से कनेक्ट होता है।',
    id: 'Terhubung ke perangkat Bluetooth yang dipasangkan.',
    it: 'Si connette ai dispositivi Bluetooth abbinati.',
    ja: 'ペアリング済みの Bluetooth 機器に接続します。',
    ko: '페어링된 블루투스 기기에 연결합니다.',
    'pt-BR': 'Conecta-se a dispositivos Bluetooth pareados.',
    ru: 'Подключается к сопряжённым устройствам Bluetooth.',
    'zh-CN': '连接已配对的蓝牙设备。',
  },
  BLUETOOTH_ADMIN: {
    en: 'Discovers and pairs Bluetooth devices.',
    ar: 'يكتشف ويقرن أجهزة البلوتوث.',
    de: 'Findet und koppelt Bluetooth-Geräte.',
    es: 'Detecta y empareja dispositivos Bluetooth.',
    fr: 'Découvre et associe des appareils Bluetooth.',
    hi: 'ब्लूटूथ डिवाइसों को खोजकर जोड़ता है।',
    id: 'Menemukan dan memasangkan perangkat Bluetooth.',
    it: 'Rileva e abbina dispositivi Bluetooth.',
    ja: 'Bluetooth 機器を検出してペアリングします。',
    ko: '블루투스 기기를 검색하고 페어링합니다.',
    'pt-BR': 'Descobre e pareia dispositivos Bluetooth.',
    ru: 'Обнаруживает и сопрягает устройства Bluetooth.',
    'zh-CN': '发现并配对蓝牙设备。',
  },
  BLUETOOTH_ADVERTISE: {
    en: 'Advertises this device to nearby Bluetooth devices.',
    ar: 'يعلن عن هذا الجهاز للأجهزة المجاورة عبر البلوتوث.',
    de: 'Macht dieses Gerät für andere Bluetooth-Geräte sichtbar.',
    es: 'Anuncia este dispositivo a otros dispositivos Bluetooth cercanos.',
    fr: 'Annonce cet appareil aux appareils Bluetooth à proximité.',
    hi: 'इस डिवाइस को आस-पास के ब्लूटूथ डिवाइसों के लिए उपलब्ध बनाता है।',
    id: 'Mengiklankan perangkat ini ke perangkat Bluetooth terdekat.',
    it: 'Annuncia questo dispositivo ai dispositivi Bluetooth vicini.',
    ja: 'この端末を近くの Bluetooth 機器に通知します。',
    ko: '주변 블루투스 기기에 이 기기를 알립니다.',
    'pt-BR': 'Anuncia este dispositivo a aparelhos Bluetooth próximos.',
    ru: 'Объявляет о наличии этого устройства соседним устройствам Bluetooth.',
    'zh-CN': '向附近的蓝牙设备宣告本设备。',
  },
  BLUETOOTH_CONNECT: {
    en: 'Connects to nearby Bluetooth devices.',
    ar: 'يتصل بأجهزة البلوتوث القريبة.',
    de: 'Verbindet sich mit Bluetooth-Geräten in der Nähe.',
    es: 'Se conecta a dispositivos Bluetooth cercanos.',
    fr: 'Se connecte aux appareils Bluetooth à proximité.',
    hi: 'पास के ब्लूटूथ डिवाइसों से कनेक्ट होता है।',
    id: 'Terhubung ke perangkat Bluetooth di sekitar.',
    it: 'Si connette a dispositivi Bluetooth nelle vicinanze.',
    ja: '近くの Bluetooth 機器に接続します。',
    ko: '주변 블루투스 기기에 연결합니다.',
    'pt-BR': 'Conecta-se a dispositivos Bluetooth próximos.',
    ru: 'Подключается к находящимся рядом устройствам Bluetooth.',
    'zh-CN': '连接附近的蓝牙设备。',
  },
  BLUETOOTH_SCAN: {
    en: 'Scans for nearby Bluetooth devices.',
    ar: 'يبحث عن أجهزة البلوتوث القريبة.',
    de: 'Sucht nach Bluetooth-Geräten in der Nähe.',
    es: 'Busca dispositivos Bluetooth cercanos.',
    fr: 'Recherche les appareils Bluetooth à proximité.',
    hi: 'पास के ब्लूटूथ डिवाइसों को स्कैन करता है।',
    id: 'Memindai perangkat Bluetooth di sekitar.',
    it: 'Cerca dispositivi Bluetooth nelle vicinanze.',
    ja: '近くの Bluetooth 機器をスキャンします。',
    ko: '주변 블루투스 기기를 검색합니다.',
    'pt-BR': 'Procura dispositivos Bluetooth próximos.',
    ru: 'Ищет находящиеся рядом устройства Bluetooth.',
    'zh-CN': '扫描附近的蓝牙设备。',
  },
  BODY_SENSORS: {
    en: 'Reads data from body sensors such as a heart-rate monitor.',
    ar: 'يقرأ بيانات مستشعرات الجسم مثل جهاز قياس نبضات القلب.',
    de: 'Liest Daten von Körpersensoren wie z. B. einem Pulsmesser.',
    es: 'Lee datos de sensores corporales como un monitor de frecuencia cardíaca.',
    fr: 'Lit les données des capteurs corporels (cardiofréquencemètre, etc.).',
    hi: 'हार्ट-रेट मॉनिटर जैसे शरीर के सेंसर से डेटा पढ़ता है।',
    id: 'Membaca data dari sensor tubuh seperti pemantau detak jantung.',
    it: 'Legge i dati dei sensori corporei come il cardiofrequenzimetro.',
    ja: '心拍計などの身体センサーからデータを読み取ります。',
    ko: '심박 측정기 등 신체 센서에서 데이터를 읽습니다.',
    'pt-BR': 'Lê dados de sensores corporais, como medidor de frequência cardíaca.',
    ru: 'Считывает данные с датчиков тела, например пульсометра.',
    'zh-CN': '读取心率等身体传感器数据。',
  },
  CALL_PHONE: {
    en: 'Initiates a phone call without going through the dialer.',
    ar: 'يبدأ مكالمة هاتفية دون المرور بشاشة الاتصال.',
    de: 'Startet einen Anruf, ohne die Wähltastatur zu öffnen.',
    es: 'Inicia llamadas sin pasar por el marcador.',
    fr: 'Lance un appel sans passer par le clavier.',
    hi: 'डायलर पर गए बिना कॉल शुरू करता है।',
    id: 'Memulai panggilan tanpa melalui dialer.',
    it: 'Avvia una chiamata senza passare dal tastierino.',
    ja: '通話画面を経由せずに電話を発信します。',
    ko: '전화 다이얼을 거치지 않고 통화를 시작합니다.',
    'pt-BR': 'Inicia uma ligação sem passar pelo discador.',
    ru: 'Начинает телефонный звонок без перехода в номеронабиратель.',
    'zh-CN': '不经过拨号界面直接拨打电话。',
  },
  CAMERA: {
    en: 'Takes pictures and records video.',
    ar: 'يلتقط الصور ويسجل الفيديو.',
    de: 'Macht Fotos und nimmt Videos auf.',
    es: 'Hace fotos y graba vídeo.',
    fr: 'Prend des photos et enregistre des vidéos.',
    hi: 'फ़ोटो लेता है और वीडियो रिकॉर्ड करता है।',
    id: 'Mengambil foto dan merekam video.',
    it: 'Scatta foto e registra video.',
    ja: '写真の撮影と動画の録画を行います。',
    ko: '사진과 동영상을 촬영합니다.',
    'pt-BR': 'Tira fotos e grava vídeos.',
    ru: 'Делает снимки и записывает видео.',
    'zh-CN': '拍摄照片和录制视频。',
  },
  GET_ACCOUNTS: {
    en: 'Reads the list of accounts on the device.',
    ar: 'يقرأ قائمة الحسابات على الجهاز.',
    de: 'Liest die Liste der Konten auf dem Gerät.',
    es: 'Lee la lista de cuentas del dispositivo.',
    fr: 'Lit la liste des comptes de l’appareil.',
    hi: 'डिवाइस पर मौजूद खातों की सूची पढ़ता है।',
    id: 'Membaca daftar akun di perangkat.',
    it: 'Legge l’elenco degli account sul dispositivo.',
    ja: '端末上のアカウント一覧を読み取ります。',
    ko: '기기의 계정 목록을 읽습니다.',
    'pt-BR': 'Lê a lista de contas no dispositivo.',
    ru: 'Читает список учётных записей на устройстве.',
    'zh-CN': '读取设备上的账号列表。',
  },
  INSTALL_SHORTCUT: {
    en: 'Adds shortcuts to the home screen without user confirmation.',
    ar: 'يضيف اختصارات إلى الشاشة الرئيسية دون تأكيد المستخدم.',
    de: 'Fügt ohne Bestätigung Verknüpfungen zum Startbildschirm hinzu.',
    es: 'Añade accesos directos a la pantalla de inicio sin confirmación.',
    fr: 'Ajoute des raccourcis à l’écran d’accueil sans confirmation.',
    hi: 'उपयोगकर्ता की पुष्टि के बिना होम स्क्रीन पर शॉर्टकट जोड़ता है।',
    id: 'Menambahkan pintasan ke layar utama tanpa konfirmasi pengguna.',
    it: 'Aggiunge scorciatoie alla schermata Home senza chiedere conferma.',
    ja: '確認なしでホーム画面にショートカットを追加します。',
    ko: '사용자 확인 없이 홈 화면에 바로가기를 추가합니다.',
    'pt-BR': 'Adiciona atalhos à tela inicial sem confirmação do usuário.',
    ru: 'Добавляет ярлыки на главный экран без подтверждения пользователя.',
    'zh-CN': '在不经用户确认的情况下添加主屏幕快捷方式。',
  },
  INTERNET: {
    en: 'Opens network connections.',
    ar: 'يفتح اتصالات الشبكة.',
    de: 'Öffnet Netzwerkverbindungen.',
    es: 'Abre conexiones de red.',
    fr: 'Ouvre des connexions réseau.',
    hi: 'नेटवर्क कनेक्शन खोलता है।',
    id: 'Membuka koneksi jaringan.',
    it: 'Apre connessioni di rete.',
    ja: 'ネットワーク接続を開きます。',
    ko: '네트워크 연결을 엽니다.',
    'pt-BR': 'Abre conexões de rede.',
    ru: 'Открывает сетевые подключения.',
    'zh-CN': '建立网络连接。',
  },
  MANAGE_ACCOUNTS: {
    en: 'Adds or removes accounts on the device.',
    ar: 'يضيف الحسابات أو يزيلها من الجهاز.',
    de: 'Fügt Konten auf dem Gerät hinzu oder entfernt sie.',
    es: 'Añade o quita cuentas del dispositivo.',
    fr: 'Ajoute ou supprime des comptes sur l’appareil.',
    hi: 'डिवाइस पर खाते जोड़ता या हटाता है।',
    id: 'Menambah atau menghapus akun di perangkat.',
    it: 'Aggiunge o rimuove account dal dispositivo.',
    ja: '端末上のアカウントを追加または削除します。',
    ko: '기기의 계정을 추가하거나 제거합니다.',
    'pt-BR': 'Adiciona ou remove contas no dispositivo.',
    ru: 'Добавляет или удаляет учётные записи на устройстве.',
    'zh-CN': '在设备上添加或删除账号。',
  },
  MANAGE_OWN_CALLS: {
    en: 'Provides an in-app calling experience that integrates with the system.',
    ar: 'يوفر تجربة مكالمات داخل التطبيق متكاملة مع النظام.',
    de: 'Bietet eine in das System integrierte In-App-Anruferfahrung.',
    es: 'Ofrece llamadas integradas en la app que se integran con el sistema.',
    fr: 'Fournit une expérience d’appel intégrée au système depuis l’app.',
    hi: 'सिस्टम के साथ एकीकृत ऐप-आधारित कॉलिंग अनुभव प्रदान करता है।',
    id: 'Menyediakan panggilan dalam aplikasi yang terintegrasi dengan sistem.',
    it: 'Fornisce un’esperienza di chiamata in-app integrata con il sistema.',
    ja: 'システムと統合されたアプリ内通話機能を提供します。',
    ko: '시스템과 통합된 인앱 통화 환경을 제공합니다.',
    'pt-BR': 'Oferece uma experiência de chamada no app integrada ao sistema.',
    ru: 'Предоставляет встроенную в систему телефонию внутри приложения.',
    'zh-CN': '提供与系统集成的应用内通话体验。',
  },
  MODIFY_AUDIO_SETTINGS: {
    en: 'Changes audio settings such as volume and routing.',
    ar: 'يغير إعدادات الصوت مثل مستوى الصوت ومسار التشغيل.',
    de: 'Ändert Audioeinstellungen wie Lautstärke und Wiedergabeweg.',
    es: 'Cambia ajustes de audio como volumen y enrutamiento.',
    fr: 'Modifie les réglages audio (volume, routage…).',
    hi: 'वॉल्यूम और राउटिंग जैसी ऑडियो सेटिंग बदलता है।',
    id: 'Mengubah pengaturan audio seperti volume dan rute.',
    it: 'Modifica le impostazioni audio come volume e instradamento.',
    ja: '音量や出力先などの音声設定を変更します。',
    ko: '음량과 출력 등 오디오 설정을 변경합니다.',
    'pt-BR': 'Altera configurações de áudio como volume e roteamento.',
    ru: 'Изменяет настройки звука, например громкость и маршрутизацию.',
    'zh-CN': '更改音量等音频设置。',
  },
  NEARBY_WIFI_DEVICES: {
    en: 'Connects to nearby Wi-Fi devices.',
    ar: 'يتصل بأجهزة Wi-Fi القريبة.',
    de: 'Verbindet sich mit WLAN-Geräten in der Nähe.',
    es: 'Se conecta a dispositivos Wi-Fi cercanos.',
    fr: 'Se connecte aux appareils Wi-Fi à proximité.',
    hi: 'पास के वाई-फ़ाई डिवाइसों से कनेक्ट होता है।',
    id: 'Terhubung ke perangkat Wi-Fi di sekitar.',
    it: 'Si connette a dispositivi Wi-Fi nelle vicinanze.',
    ja: '近くの Wi-Fi 機器に接続します。',
    ko: '주변 Wi-Fi 기기에 연결합니다.',
    'pt-BR': 'Conecta-se a dispositivos Wi-Fi próximos.',
    ru: 'Подключается к находящимся рядом устройствам Wi-Fi.',
    'zh-CN': '连接附近的 Wi-Fi 设备。',
  },
  NFC: {
    en: 'Communicates with nearby NFC tags and devices.',
    ar: 'يتواصل مع علامات وأجهزة NFC القريبة.',
    de: 'Kommuniziert mit NFC-Tags und -Geräten in der Nähe.',
    es: 'Se comunica con etiquetas y dispositivos NFC cercanos.',
    fr: 'Communique avec les tags et appareils NFC à proximité.',
    hi: 'पास के NFC टैग और डिवाइसों से संवाद करता है।',
    id: 'Berkomunikasi dengan tag dan perangkat NFC terdekat.',
    it: 'Comunica con tag e dispositivi NFC nelle vicinanze.',
    ja: '近くの NFC タグや機器と通信します。',
    ko: '주변 NFC 태그 및 기기와 통신합니다.',
    'pt-BR': 'Comunica-se com tags e dispositivos NFC próximos.',
    ru: 'Обменивается данными с расположенными рядом метками и устройствами NFC.',
    'zh-CN': '与附近的 NFC 标签和设备通信。',
  },
  POST_NOTIFICATIONS: {
    en: 'Shows notifications.',
    ar: 'يعرض الإشعارات.',
    de: 'Zeigt Benachrichtigungen an.',
    es: 'Muestra notificaciones.',
    fr: 'Affiche des notifications.',
    hi: 'सूचनाएँ दिखाता है।',
    id: 'Menampilkan notifikasi.',
    it: 'Mostra notifiche.',
    ja: '通知を表示します。',
    ko: '알림을 표시합니다.',
    'pt-BR': 'Mostra notificações.',
    ru: 'Показывает уведомления.',
    'zh-CN': '显示通知。',
  },
  READ_CALENDAR: {
    en: 'Reads your calendar events.',
    ar: 'يقرأ أحداث تقويمك.',
    de: 'Liest deine Kalendereinträge.',
    es: 'Lee tus eventos de calendario.',
    fr: 'Lit vos événements de calendrier.',
    hi: 'आपके कैलेंडर ईवेंट पढ़ता है।',
    id: 'Membaca acara kalender Anda.',
    it: 'Legge i tuoi eventi del calendario.',
    ja: 'カレンダーの予定を読み取ります。',
    ko: '캘린더 일정을 읽습니다.',
    'pt-BR': 'Lê seus eventos de calendário.',
    ru: 'Читает события вашего календаря.',
    'zh-CN': '读取您的日历事件。',
  },
  READ_CONTACTS: {
    en: 'Reads your contacts.',
    ar: 'يقرأ جهات اتصالك.',
    de: 'Liest deine Kontakte.',
    es: 'Lee tus contactos.',
    fr: 'Lit vos contacts.',
    hi: 'आपके संपर्क पढ़ता है।',
    id: 'Membaca kontak Anda.',
    it: 'Legge i tuoi contatti.',
    ja: '連絡先を読み取ります。',
    ko: '연락처를 읽습니다.',
    'pt-BR': 'Lê seus contatos.',
    ru: 'Читает ваши контакты.',
    'zh-CN': '读取您的联系人。',
  },
  READ_EXTERNAL_STORAGE: {
    en: 'Reads files from shared external storage.',
    ar: 'يقرأ الملفات من التخزين الخارجي المشترك.',
    de: 'Liest Dateien aus dem gemeinsam genutzten externen Speicher.',
    es: 'Lee archivos del almacenamiento externo compartido.',
    fr: 'Lit les fichiers du stockage externe partagé.',
    hi: 'साझा बाहरी संग्रहण से फ़ाइलें पढ़ता है।',
    id: 'Membaca file dari penyimpanan eksternal bersama.',
    it: 'Legge i file dall’archiviazione esterna condivisa.',
    ja: '共有外部ストレージのファイルを読み取ります。',
    ko: '공유 외부 저장소의 파일을 읽습니다.',
    'pt-BR': 'Lê arquivos do armazenamento externo compartilhado.',
    ru: 'Читает файлы из общего внешнего хранилища.',
    'zh-CN': '读取共享外部存储中的文件。',
  },
  READ_MEDIA_AUDIO: {
    en: 'Reads audio files from shared storage.',
    ar: 'يقرأ ملفات الصوت من التخزين المشترك.',
    de: 'Liest Audiodateien aus dem gemeinsam genutzten Speicher.',
    es: 'Lee archivos de audio del almacenamiento compartido.',
    fr: 'Lit les fichiers audio du stockage partagé.',
    hi: 'साझा संग्रहण से ऑडियो फ़ाइलें पढ़ता है।',
    id: 'Membaca file audio dari penyimpanan bersama.',
    it: 'Legge i file audio dall’archiviazione condivisa.',
    ja: '共有ストレージから音声ファイルを読み取ります。',
    ko: '공유 저장소의 오디오 파일을 읽습니다.',
    'pt-BR': 'Lê arquivos de áudio do armazenamento compartilhado.',
    ru: 'Читает аудиофайлы из общего хранилища.',
    'zh-CN': '从共享存储中读取音频文件。',
  },
  READ_MEDIA_IMAGES: {
    en: 'Reads image files from shared storage.',
    ar: 'يقرأ ملفات الصور من التخزين المشترك.',
    de: 'Liest Bilddateien aus dem gemeinsam genutzten Speicher.',
    es: 'Lee archivos de imagen del almacenamiento compartido.',
    fr: 'Lit les fichiers image du stockage partagé.',
    hi: 'साझा संग्रहण से छवि फ़ाइलें पढ़ता है।',
    id: 'Membaca file gambar dari penyimpanan bersama.',
    it: 'Legge i file immagine dall’archiviazione condivisa.',
    ja: '共有ストレージから画像ファイルを読み取ります。',
    ko: '공유 저장소의 이미지 파일을 읽습니다.',
    'pt-BR': 'Lê arquivos de imagem do armazenamento compartilhado.',
    ru: 'Читает файлы изображений из общего хранилища.',
    'zh-CN': '从共享存储中读取图片文件。',
  },
  READ_MEDIA_VIDEO: {
    en: 'Reads video files from shared storage.',
    ar: 'يقرأ ملفات الفيديو من التخزين المشترك.',
    de: 'Liest Videodateien aus dem gemeinsam genutzten Speicher.',
    es: 'Lee archivos de vídeo del almacenamiento compartido.',
    fr: 'Lit les fichiers vidéo du stockage partagé.',
    hi: 'साझा संग्रहण से वीडियो फ़ाइलें पढ़ता है।',
    id: 'Membaca file video dari penyimpanan bersama.',
    it: 'Legge i file video dall’archiviazione condivisa.',
    ja: '共有ストレージから動画ファイルを読み取ります。',
    ko: '공유 저장소의 동영상 파일을 읽습니다.',
    'pt-BR': 'Lê arquivos de vídeo do armazenamento compartilhado.',
    ru: 'Читает видеофайлы из общего хранилища.',
    'zh-CN': '从共享存储中读取视频文件。',
  },
  READ_PHONE_NUMBERS: {
    en: 'Reads the device’s phone number(s).',
    ar: 'يقرأ رقم (أو أرقام) هاتف الجهاز.',
    de: 'Liest die Telefonnummer(n) des Geräts.',
    es: 'Lee los números de teléfono del dispositivo.',
    fr: 'Lit les numéros de téléphone de l’appareil.',
    hi: 'डिवाइस के फ़ोन नंबर पढ़ता है।',
    id: 'Membaca nomor telepon perangkat.',
    it: 'Legge il/i numero/i di telefono del dispositivo.',
    ja: '端末の電話番号を読み取ります。',
    ko: '기기의 전화번호를 읽습니다.',
    'pt-BR': 'Lê os números de telefone do dispositivo.',
    ru: 'Читает номера телефона устройства.',
    'zh-CN': '读取设备的电话号码。',
  },
  READ_PHONE_STATE: {
    en: 'Reads the device’s phone state, including signal and call status.',
    ar: 'يقرأ حالة هاتف الجهاز بما فيها الإشارة وحالة المكالمة.',
    de: 'Liest den Telefonstatus des Geräts (Signal, Anrufzustand …).',
    es: 'Lee el estado del teléfono, incluida la señal y el estado de llamada.',
    fr: 'Lit l’état du téléphone (signal, état d’appel…).',
    hi: 'फ़ोन की स्थिति, सिग्नल और कॉल की स्थिति पढ़ता है।',
    id: 'Membaca status telepon, termasuk sinyal dan status panggilan.',
    it: 'Legge lo stato del telefono, incluso segnale e stato di chiamata.',
    ja: '電波状況や通話状態など、端末の電話状態を読み取ります。',
    ko: '신호 및 통화 상태를 포함한 전화 상태를 읽습니다.',
    'pt-BR': 'Lê o estado do telefone, incluindo sinal e status de chamada.',
    ru: 'Читает состояние телефона, включая сигнал и статус вызова.',
    'zh-CN': '读取手机状态，包括信号和通话状态。',
  },
  READ_PROFILE: {
    en: 'Reads the user’s profile data.',
    ar: 'يقرأ بيانات الملف الشخصي للمستخدم.',
    de: 'Liest die Profildaten des Nutzers.',
    es: 'Lee los datos del perfil del usuario.',
    fr: 'Lit les données de profil de l’utilisateur.',
    hi: 'उपयोगकर्ता का प्रोफ़ाइल डेटा पढ़ता है।',
    id: 'Membaca data profil pengguna.',
    it: 'Legge i dati del profilo utente.',
    ja: 'ユーザーのプロフィール情報を読み取ります。',
    ko: '사용자 프로필 정보를 읽습니다.',
    'pt-BR': 'Lê os dados de perfil do usuário.',
    ru: 'Читает данные профиля пользователя.',
    'zh-CN': '读取用户的个人资料。',
  },
  READ_SYNC_SETTINGS: {
    en: 'Reads the sync settings of accounts.',
    ar: 'يقرأ إعدادات مزامنة الحسابات.',
    de: 'Liest die Synchronisierungseinstellungen von Konten.',
    es: 'Lee la configuración de sincronización de las cuentas.',
    fr: 'Lit les paramètres de synchronisation des comptes.',
    hi: 'खातों की सिंक सेटिंग पढ़ता है।',
    id: 'Membaca pengaturan sinkronisasi akun.',
    it: 'Legge le impostazioni di sincronizzazione degli account.',
    ja: 'アカウントの同期設定を読み取ります。',
    ko: '계정의 동기화 설정을 읽습니다.',
    'pt-BR': 'Lê as configurações de sincronização das contas.',
    ru: 'Читает настройки синхронизации учётных записей.',
    'zh-CN': '读取账号的同步设置。',
  },
  RECEIVE_BOOT_COMPLETED: {
    en: 'Runs automatically when the device finishes booting.',
    ar: 'يعمل تلقائياً عند انتهاء تشغيل الجهاز.',
    de: 'Startet automatisch, sobald das Gerät hochgefahren ist.',
    es: 'Se ejecuta automáticamente al terminar el arranque del dispositivo.',
    fr: 'S’exécute automatiquement quand l’appareil a fini de démarrer.',
    hi: 'डिवाइस के बूट होने पर स्वचालित रूप से चलता है।',
    id: 'Berjalan otomatis saat perangkat selesai melakukan booting.',
    it: 'Si avvia automaticamente al termine dell’accensione del dispositivo.',
    ja: '端末の起動完了時に自動的に実行されます。',
    ko: '기기 부팅이 끝나면 자동으로 실행됩니다.',
    'pt-BR': 'Executa automaticamente quando o dispositivo termina de inicializar.',
    ru: 'Запускается автоматически после загрузки устройства.',
    'zh-CN': '设备完成启动后自动运行。',
  },
  RECORD_AUDIO: {
    en: 'Records audio from the microphone.',
    ar: 'يسجل الصوت من الميكروفون.',
    de: 'Nimmt Audio über das Mikrofon auf.',
    es: 'Graba audio desde el micrófono.',
    fr: 'Enregistre du son via le microphone.',
    hi: 'माइक्रोफ़ोन से ऑडियो रिकॉर्ड करता है।',
    id: 'Merekam audio dari mikrofon.',
    it: 'Registra audio dal microfono.',
    ja: 'マイクから音声を録音します。',
    ko: '마이크로 오디오를 녹음합니다.',
    'pt-BR': 'Grava áudio pelo microfone.',
    ru: 'Записывает звук с микрофона.',
    'zh-CN': '通过麦克风录制音频。',
  },
  REQUEST_INSTALL_PACKAGES: {
    en: 'Requests installation of other apps.',
    ar: 'يطلب تثبيت تطبيقات أخرى.',
    de: 'Fordert die Installation anderer Apps an.',
    es: 'Solicita la instalación de otras aplicaciones.',
    fr: 'Demande l’installation d’autres applications.',
    hi: 'अन्य ऐप्स इंस्टॉल करने का अनुरोध करता है।',
    id: 'Meminta instalasi aplikasi lain.',
    it: 'Richiede l’installazione di altre app.',
    ja: '他のアプリのインストールを要求します。',
    ko: '다른 앱의 설치를 요청합니다.',
    'pt-BR': 'Solicita a instalação de outros aplicativos.',
    ru: 'Запрашивает установку других приложений.',
    'zh-CN': '请求安装其他应用。',
  },
  SCHEDULE_EXACT_ALARM: {
    en: 'Schedules alarms that fire at an exact time.',
    ar: 'يجدول إنذارات تطلق في وقت محدد بدقة.',
    de: 'Plant Alarme, die zu einer genauen Uhrzeit ausgelöst werden.',
    es: 'Programa alarmas que se disparan a una hora exacta.',
    fr: 'Programme des alarmes déclenchées à une heure précise.',
    hi: 'सटीक समय पर सक्रिय होने वाले अलार्म शेड्यूल करता है।',
    id: 'Menjadwalkan alarm yang berbunyi pada waktu yang tepat.',
    it: 'Pianifica sveglie attivate a un orario preciso.',
    ja: '正確な時刻にアラームを発行するようスケジュールします。',
    ko: '정확한 시각에 울리는 알람을 예약합니다.',
    'pt-BR': 'Agenda alarmes que disparam em um horário exato.',
    ru: 'Планирует будильники, срабатывающие точно в назначенное время.',
    'zh-CN': '安排在精确时间触发的闹钟。',
  },
  SYSTEM_ALERT_WINDOW: {
    en: 'Displays content on top of other apps.',
    ar: 'يعرض محتوى فوق التطبيقات الأخرى.',
    de: 'Zeigt Inhalte über anderen Apps an.',
    es: 'Muestra contenido por encima de otras aplicaciones.',
    fr: 'Affiche du contenu par-dessus les autres applications.',
    hi: 'अन्य ऐप्स के ऊपर सामग्री प्रदर्शित करता है।',
    id: 'Menampilkan konten di atas aplikasi lain.',
    it: 'Mostra contenuti sopra altre app.',
    ja: '他のアプリの上にコンテンツを表示します。',
    ko: '다른 앱 위에 콘텐츠를 표시합니다.',
    'pt-BR': 'Exibe conteúdo sobre outros apps.',
    ru: 'Отображает содержимое поверх других приложений.',
    'zh-CN': '在其他应用上方显示内容。',
  },
  USE_BIOMETRIC: {
    en: 'Authenticates with biometrics such as face or fingerprint.',
    ar: 'يصادق ببيانات حيوية مثل الوجه أو بصمة الإصبع.',
    de: 'Authentifiziert per Biometrie wie Gesicht oder Fingerabdruck.',
    es: 'Autentica con biometría como el rostro o la huella.',
    fr: 'Authentifie via la biométrie (visage, empreinte…).',
    hi: 'चेहरे या उँगली के निशान जैसे बायोमेट्रिक्स से प्रमाणीकरण करता है।',
    id: 'Mengautentikasi dengan biometrik seperti wajah atau sidik jari.',
    it: 'Autentica con dati biometrici come volto o impronta.',
    ja: '顔や指紋などの生体認証を行います。',
    ko: '얼굴이나 지문 등 생체 인증을 사용합니다.',
    'pt-BR': 'Autentica com biometria, como rosto ou impressão digital.',
    ru: 'Выполняет аутентификацию по биометрии — лицу или отпечатку.',
    'zh-CN': '使用人脸或指纹等生物特征进行身份验证。',
  },
  USE_FINGERPRINT: {
    en: 'Authenticates with a fingerprint sensor.',
    ar: 'يصادق باستخدام مستشعر بصمة الإصبع.',
    de: 'Authentifiziert über den Fingerabdrucksensor.',
    es: 'Autentica usando el sensor de huella dactilar.',
    fr: 'Authentifie via le capteur d’empreinte digitale.',
    hi: 'फ़िंगरप्रिंट सेंसर से प्रमाणीकरण करता है।',
    id: 'Mengautentikasi menggunakan sensor sidik jari.',
    it: 'Autentica tramite il sensore di impronta digitale.',
    ja: '指紋センサーで認証します。',
    ko: '지문 센서로 인증합니다.',
    'pt-BR': 'Autentica usando o sensor de impressão digital.',
    ru: 'Проводит аутентификацию по отпечатку пальца.',
    'zh-CN': '使用指纹传感器进行身份验证。',
  },
  VIBRATE: {
    en: 'Controls the device’s vibrator.',
    ar: 'يتحكم في هزّاز الجهاز.',
    de: 'Steuert den Vibrationsalarm des Geräts.',
    es: 'Controla el vibrador del dispositivo.',
    fr: 'Contrôle le vibreur de l’appareil.',
    hi: 'डिवाइस के वाइब्रेटर को नियंत्रित करता है।',
    id: 'Mengontrol getaran perangkat.',
    it: 'Controlla la vibrazione del dispositivo.',
    ja: '端末のバイブレーションを制御します。',
    ko: '기기의 진동을 제어합니다.',
    'pt-BR': 'Controla a vibração do dispositivo.',
    ru: 'Управляет вибромотором устройства.',
    'zh-CN': '控制设备振动。',
  },
  WAKE_LOCK: {
    en: 'Keeps the device awake to prevent sleep.',
    ar: 'يبقي الجهاز نشطاً لمنع الدخول في وضع السكون.',
    de: 'Hält das Gerät wach, damit es nicht in den Standby geht.',
    es: 'Impide que el dispositivo entre en modo suspensión.',
    fr: 'Empêche l’appareil de se mettre en veille.',
    hi: 'डिवाइस को स्लीप मोड में जाने से रोकता है।',
    id: 'Menjaga perangkat tetap aktif agar tidak tidur.',
    it: 'Mantiene il dispositivo attivo per impedirne lo standby.',
    ja: '端末がスリープしないよう起動状態を維持します。',
    ko: '기기가 잠자기 모드로 전환되지 않도록 유지합니다.',
    'pt-BR': 'Mantém o dispositivo ativo, impedindo que entre em suspensão.',
    ru: 'Не даёт устройству перейти в режим сна.',
    'zh-CN': '让设备保持唤醒状态以防止休眠。',
  },
  WRITE_CALENDAR: {
    en: 'Modifies your calendar events.',
    ar: 'يعدّل أحداث تقويمك.',
    de: 'Ändert deine Kalendereinträge.',
    es: 'Modifica tus eventos de calendario.',
    fr: 'Modifie vos événements de calendrier.',
    hi: 'आपके कैलेंडर ईवेंट संशोधित करता है।',
    id: 'Mengubah acara kalender Anda.',
    it: 'Modifica gli eventi del tuo calendario.',
    ja: 'カレンダーの予定を変更します。',
    ko: '캘린더 일정을 수정합니다.',
    'pt-BR': 'Modifica seus eventos de calendário.',
    ru: 'Изменяет события вашего календаря.',
    'zh-CN': '修改您的日历事件。',
  },
  WRITE_CONTACTS: {
    en: 'Modifies your contacts.',
    ar: 'يعدّل جهات اتصالك.',
    de: 'Ändert deine Kontakte.',
    es: 'Modifica tus contactos.',
    fr: 'Modifie vos contacts.',
    hi: 'आपके संपर्क संशोधित करता है।',
    id: 'Mengubah kontak Anda.',
    it: 'Modifica i tuoi contatti.',
    ja: '連絡先を変更します。',
    ko: '연락처를 수정합니다.',
    'pt-BR': 'Modifica seus contatos.',
    ru: 'Изменяет ваши контакты.',
    'zh-CN': '修改您的联系人。',
  },
  WRITE_EXTERNAL_STORAGE: {
    en: 'Writes files to shared external storage.',
    ar: 'يكتب الملفات إلى التخزين الخارجي المشترك.',
    de: 'Schreibt Dateien in den gemeinsam genutzten externen Speicher.',
    es: 'Escribe archivos en el almacenamiento externo compartido.',
    fr: 'Écrit des fichiers sur le stockage externe partagé.',
    hi: 'साझा बाहरी संग्रहण में फ़ाइलें लिखता है।',
    id: 'Menulis file ke penyimpanan eksternal bersama.',
    it: 'Scrive file nell’archiviazione esterna condivisa.',
    ja: '共有外部ストレージにファイルを書き込みます。',
    ko: '공유 외부 저장소에 파일을 씁니다.',
    'pt-BR': 'Grava arquivos no armazenamento externo compartilhado.',
    ru: 'Записывает файлы в общее внешнее хранилище.',
    'zh-CN': '向共享外部存储写入文件。',
  },
  WRITE_PROFILE: {
    en: 'Modifies the user’s profile data.',
    ar: 'يعدّل بيانات الملف الشخصي للمستخدم.',
    de: 'Ändert die Profildaten des Nutzers.',
    es: 'Modifica los datos del perfil del usuario.',
    fr: 'Modifie les données de profil de l’utilisateur.',
    hi: 'उपयोगकर्ता का प्रोफ़ाइल डेटा संशोधित करता है।',
    id: 'Mengubah data profil pengguna.',
    it: 'Modifica i dati del profilo utente.',
    ja: 'ユーザーのプロフィール情報を変更します。',
    ko: '사용자 프로필 정보를 수정합니다.',
    'pt-BR': 'Modifica os dados de perfil do usuário.',
    ru: 'Изменяет данные профиля пользователя.',
    'zh-CN': '修改用户的个人资料。',
  },
  WRITE_SYNC_SETTINGS: {
    en: 'Modifies the sync settings of accounts.',
    ar: 'يعدّل إعدادات مزامنة الحسابات.',
    de: 'Ändert die Synchronisierungseinstellungen von Konten.',
    es: 'Modifica la configuración de sincronización de las cuentas.',
    fr: 'Modifie les paramètres de synchronisation des comptes.',
    hi: 'खातों की सिंक सेटिंग संशोधित करता है।',
    id: 'Mengubah pengaturan sinkronisasi akun.',
    it: 'Modifica le impostazioni di sincronizzazione degli account.',
    ja: 'アカウントの同期設定を変更します。',
    ko: '계정의 동기화 설정을 수정합니다.',
    'pt-BR': 'Modifica as configurações de sincronização das contas.',
    ru: 'Изменяет настройки синхронизации учётных записей.',
    'zh-CN': '修改账号的同步设置。',
  },
};

// -----------------------------------------------------------------------------
// Locale fallback helpers
// -----------------------------------------------------------------------------

function languageOnly(code: string): string {
  const dash = code.indexOf('-');
  return dash === -1 ? code : code.slice(0, dash);
}

function shortKey(key: string): string {
  const dot = key.lastIndexOf('.');
  return dot === -1 ? key : key.slice(dot + 1);
}

/**
 * Look up the canonical Android permission description in the requested
 * locale, falling back through language-only → en → first defined.
 */
export function lookupAndroidDescription(
  permissionKey: string,
  locale: string,
): string | undefined {
  const table = ANDROID_PERMISSION_DESCRIPTIONS[shortKey(permissionKey)];
  if (!table) return undefined;
  if (locale in table) return table[locale];
  const lang = languageOnly(locale);
  if (lang in table) return table[lang];
  for (const k of Object.keys(table)) {
    if (languageOnly(k) === lang) return table[k];
  }
  if ('en' in table) return table['en'];
  const first = Object.keys(table)[0];
  return first ? table[first] : undefined;
}
