/**
 * Minimal localization table for the small set of UI strings the template owns
 * (everything else comes from the appindex.json). Falls back to English when a
 * locale isn't covered here — the app's content remains correctly localized
 * either way.
 */

export interface UIStrings {
  about: string;
  permissions: string;
  releaseNotes: string;
  rawKeyLabel: string;
  whyNoDescription: string;
  noPermissions: string;
  versionLabel: string;
  buildLabel: string;
  bundleIdLabel: string;
  appIdLabel: string;
  privacyLink: string;
  supportLink: string;
  dependenciesLabel: string;
  /** Pagefind search input placeholder. */
  searchPlaceholder: string;
  /** Pagefind "clear search" affordance. */
  searchClearLabel: string;
  /** Pagefind empty-results message; "[SEARCH_TERM]" is interpolated. */
  searchZeroResults: string;
  /** Footer label preceding the site-generation timestamp. */
  generatedLabel: string;
  /** Heading of the per-platform download card. */
  downloadHeading: string;
  /** Hero button that opens the hosted web-dom build. */
  openWebApp: string;
  /** Header/nav link to the screenshot gallery page. */
  galleryLink: string;
  /** Gallery page heading. */
  galleryHeading: string;
  /** Gallery page subtitle. */
  galleryBlurb: string;
  /** Theme switcher labels. */
  themeLight: string;
  themeDark: string;
}

const EN: UIStrings = {
  about: 'About',
  permissions: 'Permissions',
  releaseNotes: 'Release notes',
  rawKeyLabel: 'Key',
  whyNoDescription: 'Used by the app on this platform.',
  noPermissions: 'No declared permissions.',
  versionLabel: 'Version',
  buildLabel: 'Build',
  bundleIdLabel: 'Bundle ID',
  appIdLabel: 'Application ID',
  privacyLink: 'Privacy',
  supportLink: 'Support',
  dependenciesLabel: 'Dependencies',
  searchPlaceholder: 'Search',
  searchClearLabel: 'Clear',
  searchZeroResults: 'No results for [SEARCH_TERM]',
  generatedLabel: 'Generated',
  downloadHeading: 'Download',
  openWebApp: 'Open the web app',
  galleryLink: 'Gallery',
  galleryHeading: 'Screenshots',
  galleryBlurb: 'The same app on every platform — captured by the release pipeline, not staged.',
  themeLight: 'Light',
  themeDark: 'Dark',
};

const TABLES: Record<string, Partial<UIStrings>> = {
  ar: {
    about: 'حول التطبيق',
    permissions: 'الأذونات',
    releaseNotes: 'ملاحظات الإصدار',
    rawKeyLabel: 'المفتاح',
    whyNoDescription: 'يستخدم بواسطة التطبيق على هذه المنصة.',
    noPermissions: 'لا توجد أذونات معلنة.',
    versionLabel: 'الإصدار',
    buildLabel: 'البنية',
    bundleIdLabel: 'مُعرّف الحزمة',
    appIdLabel: 'مُعرّف التطبيق',
    privacyLink: 'الخصوصية',
    supportLink: 'الدعم',
    dependenciesLabel: 'الاعتماديات',
    searchPlaceholder: 'بحث',
    searchClearLabel: 'مسح',
    searchZeroResults: 'لا توجد نتائج لـ [SEARCH_TERM]',
    generatedLabel: 'تم الإنشاء',
  },
  cs: {
    about: 'O aplikaci',
    permissions: 'Oprávnění',
    releaseNotes: 'Poznámky k vydání',
    rawKeyLabel: 'Klíč',
    whyNoDescription: 'Používá aplikace na této platformě.',
    noPermissions: 'Žádná deklarovaná oprávnění.',
    versionLabel: 'Verze',
    buildLabel: 'Sestavení',
    bundleIdLabel: 'ID balíčku',
    appIdLabel: 'ID aplikace',
    privacyLink: 'Soukromí',
    supportLink: 'Podpora',
    dependenciesLabel: 'Závislosti',
    searchPlaceholder: 'Hledat',
    searchClearLabel: 'Vymazat',
    searchZeroResults: 'Žádné výsledky pro [SEARCH_TERM]',
    generatedLabel: 'Vygenerováno',
  },
  de: {
    about: 'Über die App',
    permissions: 'Berechtigungen',
    releaseNotes: 'Versionshinweise',
    rawKeyLabel: 'Schlüssel',
    whyNoDescription: 'Wird von der App auf dieser Plattform verwendet.',
    noPermissions: 'Keine deklarierten Berechtigungen.',
    versionLabel: 'Version',
    buildLabel: 'Build',
    bundleIdLabel: 'Bundle-ID',
    appIdLabel: 'App-ID',
    privacyLink: 'Datenschutz',
    supportLink: 'Support',
    dependenciesLabel: 'Abhängigkeiten',
    searchPlaceholder: 'Suchen',
    searchClearLabel: 'Löschen',
    searchZeroResults: 'Keine Ergebnisse für [SEARCH_TERM]',
    generatedLabel: 'Erstellt am',
  },
  es: {
    about: 'Acerca de',
    permissions: 'Permisos',
    releaseNotes: 'Novedades',
    rawKeyLabel: 'Clave',
    whyNoDescription: 'Usado por la app en esta plataforma.',
    noPermissions: 'Sin permisos declarados.',
    versionLabel: 'Versión',
    buildLabel: 'Compilación',
    bundleIdLabel: 'ID del paquete',
    appIdLabel: 'ID de la aplicación',
    privacyLink: 'Privacidad',
    supportLink: 'Soporte',
    dependenciesLabel: 'Dependencias',
    searchPlaceholder: 'Buscar',
    searchClearLabel: 'Borrar',
    searchZeroResults: 'Sin resultados para [SEARCH_TERM]',
    generatedLabel: 'Generado el',
  },
  fr: {
    about: 'À propos',
    permissions: 'Autorisations',
    releaseNotes: 'Notes de version',
    rawKeyLabel: 'Clé',
    whyNoDescription: 'Utilisé par l’app sur cette plateforme.',
    noPermissions: 'Aucune autorisation déclarée.',
    versionLabel: 'Version',
    buildLabel: 'Build',
    bundleIdLabel: 'ID du bundle',
    appIdLabel: 'ID de l’application',
    privacyLink: 'Confidentialité',
    supportLink: 'Assistance',
    dependenciesLabel: 'Dépendances',
    searchPlaceholder: 'Rechercher',
    searchClearLabel: 'Effacer',
    searchZeroResults: 'Aucun résultat pour [SEARCH_TERM]',
    generatedLabel: 'Généré le',
  },
  hi: {
    about: 'ऐप के बारे में',
    permissions: 'अनुमतियाँ',
    releaseNotes: 'रिलीज़ नोट्स',
    rawKeyLabel: 'कुंजी',
    whyNoDescription: 'इस प्लेटफ़ॉर्म पर ऐप द्वारा उपयोग किया जाता है।',
    noPermissions: 'कोई घोषित अनुमतियाँ नहीं।',
    versionLabel: 'संस्करण',
    buildLabel: 'बिल्ड',
    bundleIdLabel: 'बंडल आईडी',
    appIdLabel: 'ऐप्लिकेशन आईडी',
    privacyLink: 'गोपनीयता',
    supportLink: 'सहायता',
    dependenciesLabel: 'निर्भरताएँ',
    searchPlaceholder: 'खोजें',
    searchClearLabel: 'साफ़ करें',
    searchZeroResults: '[SEARCH_TERM] के लिए कोई परिणाम नहीं',
    generatedLabel: 'उत्पन्न',
  },
  id: {
    about: 'Tentang aplikasi',
    permissions: 'Izin',
    releaseNotes: 'Catatan rilis',
    rawKeyLabel: 'Kunci',
    whyNoDescription: 'Digunakan oleh aplikasi di platform ini.',
    noPermissions: 'Tidak ada izin yang dideklarasikan.',
    versionLabel: 'Versi',
    buildLabel: 'Build',
    bundleIdLabel: 'ID bundel',
    appIdLabel: 'ID aplikasi',
    privacyLink: 'Privasi',
    supportLink: 'Dukungan',
    dependenciesLabel: 'Dependensi',
    searchPlaceholder: 'Cari',
    searchClearLabel: 'Bersihkan',
    searchZeroResults: 'Tidak ada hasil untuk [SEARCH_TERM]',
    generatedLabel: 'Dibuat pada',
  },
  it: {
    about: 'Informazioni',
    permissions: 'Autorizzazioni',
    releaseNotes: 'Note di versione',
    rawKeyLabel: 'Chiave',
    whyNoDescription: 'Utilizzato dall’app su questa piattaforma.',
    noPermissions: 'Nessuna autorizzazione dichiarata.',
    versionLabel: 'Versione',
    buildLabel: 'Build',
    bundleIdLabel: 'ID bundle',
    appIdLabel: 'ID applicazione',
    privacyLink: 'Privacy',
    supportLink: 'Supporto',
    dependenciesLabel: 'Dipendenze',
    searchPlaceholder: 'Cerca',
    searchClearLabel: 'Cancella',
    searchZeroResults: 'Nessun risultato per [SEARCH_TERM]',
    generatedLabel: 'Generato il',
  },
  ja: {
    about: 'アプリについて',
    permissions: '権限',
    releaseNotes: 'リリースノート',
    rawKeyLabel: 'キー',
    whyNoDescription: 'このプラットフォームでアプリが使用します。',
    noPermissions: '宣言された権限はありません。',
    versionLabel: 'バージョン',
    buildLabel: 'ビルド',
    bundleIdLabel: 'バンドル ID',
    appIdLabel: 'アプリ ID',
    privacyLink: 'プライバシー',
    supportLink: 'サポート',
    dependenciesLabel: '依存関係',
    searchPlaceholder: '検索',
    searchClearLabel: 'クリア',
    searchZeroResults: '[SEARCH_TERM] の検索結果はありません',
    generatedLabel: '生成日時',
  },
  ko: {
    about: '앱 정보',
    permissions: '권한',
    releaseNotes: '릴리스 노트',
    rawKeyLabel: '키',
    whyNoDescription: '이 플랫폼에서 앱이 사용합니다.',
    noPermissions: '선언된 권한이 없습니다.',
    versionLabel: '버전',
    buildLabel: '빌드',
    bundleIdLabel: '번들 ID',
    appIdLabel: '앱 ID',
    privacyLink: '개인정보 처리방침',
    supportLink: '지원',
    dependenciesLabel: '종속성',
    searchPlaceholder: '검색',
    searchClearLabel: '지우기',
    searchZeroResults: '[SEARCH_TERM]에 대한 결과가 없습니다',
    generatedLabel: '생성됨',
  },
  ms: {
    about: 'Tentang aplikasi',
    permissions: 'Kebenaran',
    releaseNotes: 'Nota keluaran',
    rawKeyLabel: 'Kunci',
    whyNoDescription: 'Digunakan oleh aplikasi pada platform ini.',
    noPermissions: 'Tiada kebenaran yang diisytiharkan.',
    versionLabel: 'Versi',
    buildLabel: 'Binaan',
    bundleIdLabel: 'ID bundel',
    appIdLabel: 'ID aplikasi',
    privacyLink: 'Privasi',
    supportLink: 'Sokongan',
    dependenciesLabel: 'Kebergantungan',
    searchPlaceholder: 'Cari',
    searchClearLabel: 'Kosongkan',
    searchZeroResults: 'Tiada hasil untuk [SEARCH_TERM]',
    generatedLabel: 'Dijana pada',
  },
  nl: {
    about: 'Over de app',
    permissions: 'Machtigingen',
    releaseNotes: 'Releaseopmerkingen',
    rawKeyLabel: 'Sleutel',
    whyNoDescription: 'Wordt door de app op dit platform gebruikt.',
    noPermissions: 'Geen gedeclareerde machtigingen.',
    versionLabel: 'Versie',
    buildLabel: 'Build',
    bundleIdLabel: 'Bundel-ID',
    appIdLabel: 'App-ID',
    privacyLink: 'Privacy',
    supportLink: 'Ondersteuning',
    dependenciesLabel: 'Afhankelijkheden',
    searchPlaceholder: 'Zoeken',
    searchClearLabel: 'Wissen',
    searchZeroResults: 'Geen resultaten voor [SEARCH_TERM]',
    generatedLabel: 'Gegenereerd op',
  },
  pl: {
    about: 'O aplikacji',
    permissions: 'Uprawnienia',
    releaseNotes: 'Informacje o wersji',
    rawKeyLabel: 'Klucz',
    whyNoDescription: 'Używane przez aplikację na tej platformie.',
    noPermissions: 'Brak zadeklarowanych uprawnień.',
    versionLabel: 'Wersja',
    buildLabel: 'Kompilacja',
    bundleIdLabel: 'Identyfikator pakietu',
    appIdLabel: 'Identyfikator aplikacji',
    privacyLink: 'Prywatność',
    supportLink: 'Pomoc',
    dependenciesLabel: 'Zależności',
    searchPlaceholder: 'Szukaj',
    searchClearLabel: 'Wyczyść',
    searchZeroResults: 'Brak wyników dla [SEARCH_TERM]',
    generatedLabel: 'Wygenerowano',
  },
  pt: {
    about: 'Sobre',
    permissions: 'Permissões',
    releaseNotes: 'Notas da versão',
    rawKeyLabel: 'Chave',
    whyNoDescription: 'Usado pelo app nesta plataforma.',
    noPermissions: 'Sem permissões declaradas.',
    versionLabel: 'Versão',
    buildLabel: 'Build',
    bundleIdLabel: 'ID do bundle',
    appIdLabel: 'ID do aplicativo',
    privacyLink: 'Privacidade',
    supportLink: 'Suporte',
    dependenciesLabel: 'Dependências',
    searchPlaceholder: 'Pesquisar',
    searchClearLabel: 'Limpar',
    searchZeroResults: 'Sem resultados para [SEARCH_TERM]',
    generatedLabel: 'Gerado em',
  },
  ru: {
    about: 'О приложении',
    permissions: 'Разрешения',
    releaseNotes: 'Заметки о выпуске',
    rawKeyLabel: 'Ключ',
    whyNoDescription: 'Используется приложением на этой платформе.',
    noPermissions: 'Разрешения не заявлены.',
    versionLabel: 'Версия',
    buildLabel: 'Сборка',
    bundleIdLabel: 'ID пакета',
    appIdLabel: 'ID приложения',
    privacyLink: 'Конфиденциальность',
    supportLink: 'Поддержка',
    dependenciesLabel: 'Зависимости',
    searchPlaceholder: 'Поиск',
    searchClearLabel: 'Очистить',
    searchZeroResults: 'Нет результатов для [SEARCH_TERM]',
    generatedLabel: 'Создано',
  },
  th: {
    about: 'เกี่ยวกับแอป',
    permissions: 'สิทธิ์',
    releaseNotes: 'บันทึกประจำรุ่น',
    rawKeyLabel: 'คีย์',
    whyNoDescription: 'แอปใช้งานบนแพลตฟอร์มนี้',
    noPermissions: 'ไม่มีสิทธิ์ที่ประกาศไว้',
    versionLabel: 'เวอร์ชัน',
    buildLabel: 'บิลด์',
    bundleIdLabel: 'รหัสบันเดิล',
    appIdLabel: 'รหัสแอปพลิเคชัน',
    privacyLink: 'ความเป็นส่วนตัว',
    supportLink: 'การสนับสนุน',
    dependenciesLabel: 'การอ้างอิง',
    searchPlaceholder: 'ค้นหา',
    searchClearLabel: 'ล้าง',
    searchZeroResults: 'ไม่พบผลลัพธ์สำหรับ [SEARCH_TERM]',
    generatedLabel: 'สร้างเมื่อ',
  },
  tr: {
    about: 'Uygulama hakkında',
    permissions: 'İzinler',
    releaseNotes: 'Sürüm notları',
    rawKeyLabel: 'Anahtar',
    whyNoDescription: 'Uygulama tarafından bu platformda kullanılır.',
    noPermissions: 'Bildirilen izin yok.',
    versionLabel: 'Sürüm',
    buildLabel: 'Derleme',
    bundleIdLabel: 'Paket kimliği',
    appIdLabel: 'Uygulama kimliği',
    privacyLink: 'Gizlilik',
    supportLink: 'Destek',
    dependenciesLabel: 'Bağımlılıklar',
    searchPlaceholder: 'Ara',
    searchClearLabel: 'Temizle',
    searchZeroResults: '[SEARCH_TERM] için sonuç bulunamadı',
    generatedLabel: 'Oluşturulma',
  },
  uk: {
    about: 'Про застосунок',
    permissions: 'Дозволи',
    releaseNotes: 'Примітки до випуску',
    rawKeyLabel: 'Ключ',
    whyNoDescription: 'Використовується застосунком на цій платформі.',
    noPermissions: 'Дозволи не оголошено.',
    versionLabel: 'Версія',
    buildLabel: 'Збірка',
    bundleIdLabel: 'ID пакета',
    appIdLabel: 'ID застосунку',
    privacyLink: 'Конфіденційність',
    supportLink: 'Підтримка',
    dependenciesLabel: 'Залежності',
    searchPlaceholder: 'Пошук',
    searchClearLabel: 'Очистити',
    searchZeroResults: 'Немає результатів для [SEARCH_TERM]',
    generatedLabel: 'Створено',
  },
  vi: {
    about: 'Giới thiệu về ứng dụng',
    permissions: 'Quyền',
    releaseNotes: 'Ghi chú phát hành',
    rawKeyLabel: 'Khóa',
    whyNoDescription: 'Được ứng dụng sử dụng trên nền tảng này.',
    noPermissions: 'Không có quyền nào được khai báo.',
    versionLabel: 'Phiên bản',
    buildLabel: 'Bản dựng',
    bundleIdLabel: 'ID gói',
    appIdLabel: 'ID ứng dụng',
    privacyLink: 'Quyền riêng tư',
    supportLink: 'Hỗ trợ',
    dependenciesLabel: 'Phụ thuộc',
    searchPlaceholder: 'Tìm kiếm',
    searchClearLabel: 'Xóa',
    searchZeroResults: 'Không có kết quả cho [SEARCH_TERM]',
    generatedLabel: 'Được tạo lúc',
  },
  zh: {
    about: '关于',
    permissions: '权限',
    releaseNotes: '版本说明',
    rawKeyLabel: '键',
    whyNoDescription: '此平台上的应用会使用。',
    noPermissions: '未声明任何权限。',
    versionLabel: '版本',
    buildLabel: '构建',
    bundleIdLabel: 'Bundle ID',
    appIdLabel: '应用 ID',
    privacyLink: '隐私',
    supportLink: '支持',
    dependenciesLabel: '依赖项',
    searchPlaceholder: '搜索',
    searchClearLabel: '清除',
    searchZeroResults: '没有 [SEARCH_TERM] 的结果',
    generatedLabel: '生成时间',
  },
  'zh-Hant': {
    about: '關於',
    permissions: '權限',
    releaseNotes: '版本資訊',
    rawKeyLabel: '鍵',
    whyNoDescription: '此平台上的應用程式會使用。',
    noPermissions: '未宣告任何權限。',
    versionLabel: '版本',
    buildLabel: '組建',
    bundleIdLabel: 'Bundle ID',
    appIdLabel: '應用程式 ID',
    privacyLink: '隱私權',
    supportLink: '支援',
    dependenciesLabel: '相依性',
    searchPlaceholder: '搜尋',
    searchClearLabel: '清除',
    searchZeroResults: '沒有 [SEARCH_TERM] 的結果',
    generatedLabel: '產生時間',
  },
};

export function uiStrings(locale: string): UIStrings {
  // English first, then each subtag prefix from broadest to narrowest, so the more specific
  // table always wins the key: "zh-Hant-TW" picks up "zh" and then "zh-Hant". The order is the
  // whole point — apply "zh" last and Traditional Chinese pages render the Simplified strings.
  const parts = locale.split('-');
  let out: UIStrings = { ...EN };
  for (let i = 1; i <= parts.length; i++) {
    out = { ...out, ...(TABLES[parts.slice(0, i).join('-')] ?? {}) };
  }
  return out;
}
