/**
 * Minimal localization table for the small set of UI strings the template owns
 * (everything else comes from the appindex.json). Falls back to English when a
 * locale isn't covered here — the app's content remains correctly localized
 * either way.
 */

export interface UIStrings {
  about: string;
  permissions: string;
  releaseNotes: string;
  rawKeyLabel: string;
  whyNoDescription: string;
  noPermissions: string;
  versionLabel: string;
  buildLabel: string;
  bundleIdLabel: string;
  appIdLabel: string;
  privacyLink: string;
  supportLink: string;
  dependenciesLabel: string;
  /** Pagefind search input placeholder. */
  searchPlaceholder: string;
  /** Pagefind "clear search" affordance. */
  searchClearLabel: string;
  /** Pagefind empty-results message; "[SEARCH_TERM]" is interpolated. */
  searchZeroResults: string;
  /** Footer label preceding the site-generation timestamp. */
  generatedLabel: string;
  /** Footer link to the project's source repository. */
  sourceLink: string;
  /** Footer link to the project's latest release. */
  releaseLink: string;
  /** Footer attribution beside the Day mark. Carries the product name, because word order
      around it differs by language. */
  builtWith: string;
  /** Heading of the per-platform download card. */
  downloadHeading: string;
  /** Hero button that opens the hosted web-dom build. */
  openWebApp: string;
  /** Header/nav link to the screenshot gallery page. */
  galleryLink: string;
  /** Gallery page heading. */
  galleryHeading: string;
  /** Gallery page subtitle; "[DAYSCRIPT]" is interpolated — the docs link in the visible
      subtitle, the bare word in the page description. */
  galleryBlurb: string;
  /** Theme switcher labels. */
  themeLight: string;
  themeDark: string;
  /** The toolbar QR code's accessible name and overlay title; "[APP]" is the app's name. */
  qrTitle: string;
  /** Under the full-screen QR code: what scanning it does. */
  qrHint: string;
  /** Accessible name of the build-channel picker above the platform picker (lib/channels.ts). */
  versionPickerLabel: string;
  /** The one-line notice on a development channel's pages; "[BRANCH]" is the branch the build
      came from. One string rather than a heading and a body: it has to read as a single
      sentence on one line, and splitting a sentence in two breaks word order in translation. */
  devBuildInline: string;
  /** The notice's link to the released version; "[VERSION]" is that version. */
  devBuildReleaseLink: string;
  /** The notice's second line when the project has published no release at all. */
  devBuildNoRelease: string;
  /** Under a development channel's download card: where those packages came from. */
  devBuildDownloadNote: string;
  /** About-card row naming the commit a development build came from. */
  commitLabel: string;
}

const EN: UIStrings = {
  about: 'About',
  permissions: 'Permissions',
  releaseNotes: 'Release notes',
  rawKeyLabel: 'Key',
  whyNoDescription: 'Used by the app on this platform.',
  noPermissions: 'No declared permissions.',
  versionLabel: 'Version',
  buildLabel: 'Build',
  bundleIdLabel: 'Bundle ID',
  appIdLabel: 'Application ID',
  privacyLink: 'Privacy',
  supportLink: 'Support',
  dependenciesLabel: 'Dependencies',
  searchPlaceholder: 'Search',
  searchClearLabel: 'Clear',
  searchZeroResults: 'No results for [SEARCH_TERM]',
  generatedLabel: 'Generated',
  sourceLink: 'Source',
  releaseLink: 'Release',
  builtWith: 'Built with Day',
  downloadHeading: 'Download',
  openWebApp: 'Open the web app',
  galleryLink: 'Gallery',
  galleryHeading: 'Screenshots',
  galleryBlurb:
    'These screenshots are taken automatically by the continuous-integration [DAYSCRIPT] walkthrough for each toolkit.',
  themeLight: 'Light',
  themeDark: 'Dark',
  qrTitle: 'Landing page for the [APP] app',
  qrHint: 'Scan with a phone to open this page.',
  versionPickerLabel: 'Version',
  devBuildInline: 'Development build of [BRANCH]. It can be unstable.',
  devBuildReleaseLink: 'Get the [VERSION] release instead',
  devBuildNoRelease: 'No release has been published yet.',
  devBuildDownloadNote: 'Packed by the last CI run and signed for development.',
  commitLabel: 'Commit',
};

const TABLES: Record<string, Partial<UIStrings>> = {
  ar: {
    qrTitle: 'الصفحة الرئيسية لتطبيق [APP]',
    qrHint: 'امسح الرمز بالهاتف لفتح هذه الصفحة.',
    about: 'حول التطبيق',
    permissions: 'الأذونات',
    releaseNotes: 'ملاحظات الإصدار',
    rawKeyLabel: 'المفتاح',
    whyNoDescription: 'يستخدم بواسطة التطبيق على هذه المنصة.',
    noPermissions: 'لا توجد أذونات معلنة.',
    versionLabel: 'الإصدار',
    buildLabel: 'البنية',
    bundleIdLabel: 'مُعرّف الحزمة',
    appIdLabel: 'مُعرّف التطبيق',
    privacyLink: 'الخصوصية',
    supportLink: 'الدعم',
    dependenciesLabel: 'الاعتماديات',
    searchPlaceholder: 'بحث',
    searchClearLabel: 'مسح',
    searchZeroResults: 'لا توجد نتائج لـ [SEARCH_TERM]',
    generatedLabel: 'تم الإنشاء',
    sourceLink: 'المصدر',
    releaseLink: 'الإصدار',
    builtWith: 'أُنشئ باستخدام Day',
    galleryLink: 'المعرض',
    galleryHeading: 'لقطات الشاشة',
    galleryBlurb:
      'تُلتقط هذه اللقطات تلقائيًا عبر جولة [DAYSCRIPT] في التكامل المستمر لكل عدة أدوات.',
    versionPickerLabel: 'الإصدار',
    devBuildInline: 'إصدار تطويري من [BRANCH]. قد يكون غير مستقر.',
    devBuildReleaseLink: 'احصل على الإصدار [VERSION] بدلاً من ذلك',
    devBuildNoRelease: 'لم يُنشر أي إصدار بعد.',
    devBuildDownloadNote: 'حُزمت في آخر تشغيل للتكامل المستمر ووُقّعت للتطوير.',
    commitLabel: 'التزام',
  },
  cs: {
    about: 'O aplikaci',
    permissions: 'Oprávnění',
    releaseNotes: 'Poznámky k vydání',
    rawKeyLabel: 'Klíč',
    whyNoDescription: 'Používá aplikace na této platformě.',
    noPermissions: 'Žádná deklarovaná oprávnění.',
    versionLabel: 'Verze',
    buildLabel: 'Sestavení',
    bundleIdLabel: 'ID balíčku',
    appIdLabel: 'ID aplikace',
    privacyLink: 'Soukromí',
    supportLink: 'Podpora',
    dependenciesLabel: 'Závislosti',
    searchPlaceholder: 'Hledat',
    searchClearLabel: 'Vymazat',
    searchZeroResults: 'Žádné výsledky pro [SEARCH_TERM]',
    generatedLabel: 'Vygenerováno',
    sourceLink: 'Zdrojový kód',
    releaseLink: 'Vydání',
    builtWith: 'Vytvořeno pomocí Day',
    versionPickerLabel: 'Verze',
    devBuildInline: 'Vývojové sestavení větve [BRANCH]. Může být nestabilní.',
    devBuildReleaseLink: 'Stáhnout raději vydání [VERSION]',
    devBuildNoRelease: 'Zatím nebylo zveřejněno žádné vydání.',
    devBuildDownloadNote: 'Zabaleno posledním během CI a podepsáno pro vývoj.',
  },
  de: {
    qrTitle: 'Startseite der App [APP]',
    qrHint: 'Mit dem Telefon scannen, um diese Seite zu öffnen.',
    about: 'Über die App',
    permissions: 'Berechtigungen',
    releaseNotes: 'Versionshinweise',
    rawKeyLabel: 'Schlüssel',
    whyNoDescription: 'Wird von der App auf dieser Plattform verwendet.',
    noPermissions: 'Keine deklarierten Berechtigungen.',
    versionLabel: 'Version',
    buildLabel: 'Build',
    bundleIdLabel: 'Bundle-ID',
    appIdLabel: 'App-ID',
    privacyLink: 'Datenschutz',
    supportLink: 'Support',
    dependenciesLabel: 'Abhängigkeiten',
    searchPlaceholder: 'Suchen',
    searchClearLabel: 'Löschen',
    searchZeroResults: 'Keine Ergebnisse für [SEARCH_TERM]',
    generatedLabel: 'Erstellt am',
    sourceLink: 'Quellcode',
    releaseLink: 'Release',
    builtWith: 'Erstellt mit Day',
    versionPickerLabel: 'Version',
    devBuildInline: 'Entwicklungs-Build von [BRANCH]. Kann instabil sein.',
    devBuildReleaseLink: 'Stattdessen Release [VERSION] laden',
    devBuildNoRelease: 'Es wurde noch kein Release veröffentlicht.',
    devBuildDownloadNote: 'Im letzten CI-Lauf gepackt und für die Entwicklung signiert.',
  },
  es: {
    qrTitle: 'Página de inicio de la app [APP]',
    qrHint: 'Escanea con el teléfono para abrir esta página.',
    about: 'Acerca de',
    permissions: 'Permisos',
    releaseNotes: 'Novedades',
    rawKeyLabel: 'Clave',
    whyNoDescription: 'Usado por la app en esta plataforma.',
    noPermissions: 'Sin permisos declarados.',
    versionLabel: 'Versión',
    buildLabel: 'Compilación',
    bundleIdLabel: 'ID del paquete',
    appIdLabel: 'ID de la aplicación',
    privacyLink: 'Privacidad',
    supportLink: 'Soporte',
    dependenciesLabel: 'Dependencias',
    searchPlaceholder: 'Buscar',
    searchClearLabel: 'Borrar',
    searchZeroResults: 'Sin resultados para [SEARCH_TERM]',
    generatedLabel: 'Generado el',
    sourceLink: 'Código fuente',
    releaseLink: 'Lanzamiento',
    builtWith: 'Creado con Day',
    versionPickerLabel: 'Versión',
    devBuildInline: 'Compilación de desarrollo de [BRANCH]. Puede ser inestable.',
    devBuildReleaseLink: 'Descarga la versión [VERSION] en su lugar',
    devBuildNoRelease: 'Todavía no se ha publicado ninguna versión.',
    devBuildDownloadNote: 'Empaquetado en la última ejecución de CI y firmado para desarrollo.',
  },
  fr: {
    qrTitle: 'Page d’accueil de l’app [APP]',
    qrHint: 'Scannez avec un téléphone pour ouvrir cette page.',
    about: 'À propos',
    permissions: 'Autorisations',
    releaseNotes: 'Notes de version',
    rawKeyLabel: 'Clé',
    whyNoDescription: 'Utilisé par l’app sur cette plateforme.',
    noPermissions: 'Aucune autorisation déclarée.',
    versionLabel: 'Version',
    buildLabel: 'Build',
    bundleIdLabel: 'ID du bundle',
    appIdLabel: 'ID de l’application',
    privacyLink: 'Confidentialité',
    supportLink: 'Assistance',
    dependenciesLabel: 'Dépendances',
    searchPlaceholder: 'Rechercher',
    searchClearLabel: 'Effacer',
    searchZeroResults: 'Aucun résultat pour [SEARCH_TERM]',
    generatedLabel: 'Généré le',
    sourceLink: 'Code source',
    releaseLink: 'Publication',
    builtWith: 'Créé avec Day',
    galleryLink: 'Galerie',
    galleryHeading: 'Captures d’écran',
    galleryBlurb:
      'Ces captures d’écran sont prises automatiquement par le parcours [DAYSCRIPT] d’intégration continue, pour chaque toolkit.',
    versionPickerLabel: 'Version',
    devBuildInline: 'Build de développement de [BRANCH]. Peut être instable.',
    devBuildReleaseLink: 'Télécharger plutôt la version [VERSION]',
    devBuildNoRelease: 'Aucune version n’a encore été publiée.',
    devBuildDownloadNote: 'Empaqueté par la dernière exécution CI et signé pour le développement.',
  },
  hi: {
    about: 'ऐप के बारे में',
    permissions: 'अनुमतियाँ',
    releaseNotes: 'रिलीज़ नोट्स',
    rawKeyLabel: 'कुंजी',
    whyNoDescription: 'इस प्लेटफ़ॉर्म पर ऐप द्वारा उपयोग किया जाता है।',
    noPermissions: 'कोई घोषित अनुमतियाँ नहीं।',
    versionLabel: 'संस्करण',
    buildLabel: 'बिल्ड',
    bundleIdLabel: 'बंडल आईडी',
    appIdLabel: 'ऐप्लिकेशन आईडी',
    privacyLink: 'गोपनीयता',
    supportLink: 'सहायता',
    dependenciesLabel: 'निर्भरताएँ',
    searchPlaceholder: 'खोजें',
    searchClearLabel: 'साफ़ करें',
    searchZeroResults: '[SEARCH_TERM] के लिए कोई परिणाम नहीं',
    generatedLabel: 'उत्पन्न',
    sourceLink: 'स्रोत',
    releaseLink: 'रिलीज़',
    builtWith: 'Day से निर्मित',
    versionPickerLabel: 'संस्करण',
    devBuildInline: '[BRANCH] का विकास बिल्ड। यह अस्थिर हो सकता है।',
    devBuildReleaseLink: 'इसके बजाय [VERSION] रिलीज़ लें',
    devBuildNoRelease: 'अभी तक कोई रिलीज़ प्रकाशित नहीं हुई है।',
    devBuildDownloadNote: 'पिछले CI रन में पैक किया गया और विकास के लिए हस्ताक्षरित।',
    commitLabel: 'कमिट',
  },
  id: {
    about: 'Tentang aplikasi',
    permissions: 'Izin',
    releaseNotes: 'Catatan rilis',
    rawKeyLabel: 'Kunci',
    whyNoDescription: 'Digunakan oleh aplikasi di platform ini.',
    noPermissions: 'Tidak ada izin yang dideklarasikan.',
    versionLabel: 'Versi',
    buildLabel: 'Build',
    bundleIdLabel: 'ID bundel',
    appIdLabel: 'ID aplikasi',
    privacyLink: 'Privasi',
    supportLink: 'Dukungan',
    dependenciesLabel: 'Dependensi',
    searchPlaceholder: 'Cari',
    searchClearLabel: 'Bersihkan',
    searchZeroResults: 'Tidak ada hasil untuk [SEARCH_TERM]',
    generatedLabel: 'Dibuat pada',
    sourceLink: 'Kode sumber',
    releaseLink: 'Rilis',
    builtWith: 'Dibuat dengan Day',
    versionPickerLabel: 'Versi',
    devBuildInline: 'Build pengembangan dari [BRANCH]. Bisa tidak stabil.',
    devBuildReleaseLink: 'Ambil rilis [VERSION] saja',
    devBuildNoRelease: 'Belum ada rilis yang diterbitkan.',
    devBuildDownloadNote: 'Dikemas oleh proses CI terakhir dan ditandatangani untuk pengembangan.',
  },
  it: {
    qrTitle: 'Pagina iniziale dell’app [APP]',
    qrHint: 'Inquadra con il telefono per aprire questa pagina.',
    about: 'Informazioni',
    permissions: 'Autorizzazioni',
    releaseNotes: 'Note di versione',
    rawKeyLabel: 'Chiave',
    whyNoDescription: 'Utilizzato dall’app su questa piattaforma.',
    noPermissions: 'Nessuna autorizzazione dichiarata.',
    versionLabel: 'Versione',
    buildLabel: 'Build',
    bundleIdLabel: 'ID bundle',
    appIdLabel: 'ID applicazione',
    privacyLink: 'Privacy',
    supportLink: 'Supporto',
    dependenciesLabel: 'Dipendenze',
    searchPlaceholder: 'Cerca',
    searchClearLabel: 'Cancella',
    searchZeroResults: 'Nessun risultato per [SEARCH_TERM]',
    generatedLabel: 'Generato il',
    sourceLink: 'Codice sorgente',
    releaseLink: 'Rilascio',
    builtWith: 'Creato con Day',
    versionPickerLabel: 'Versione',
    devBuildInline: 'Build di sviluppo di [BRANCH]. Può essere instabile.',
    devBuildReleaseLink: 'Scarica invece la versione [VERSION]',
    devBuildNoRelease: 'Non è ancora stata pubblicata nessuna versione.',
    devBuildDownloadNote: 'Pacchettizzato dall’ultima esecuzione CI e firmato per lo sviluppo.',
  },
  ja: {
    qrTitle: '[APP] アプリのランディングページ',
    qrHint: 'スマートフォンで読み取るとこのページが開きます。',
    about: 'アプリについて',
    permissions: '権限',
    releaseNotes: 'リリースノート',
    rawKeyLabel: 'キー',
    whyNoDescription: 'このプラットフォームでアプリが使用します。',
    noPermissions: '宣言された権限はありません。',
    versionLabel: 'バージョン',
    buildLabel: 'ビルド',
    bundleIdLabel: 'バンドル ID',
    appIdLabel: 'アプリ ID',
    privacyLink: 'プライバシー',
    supportLink: 'サポート',
    dependenciesLabel: '依存関係',
    searchPlaceholder: '検索',
    searchClearLabel: 'クリア',
    searchZeroResults: '[SEARCH_TERM] の検索結果はありません',
    generatedLabel: '生成日時',
    sourceLink: 'ソースコード',
    releaseLink: 'リリース',
    builtWith: 'Day で作成',
    versionPickerLabel: 'バージョン',
    devBuildInline: '[BRANCH] の開発ビルドです。動作が不安定な場合があります。',
    devBuildReleaseLink: '代わりに [VERSION] リリースを入手',
    devBuildNoRelease: 'まだリリースは公開されていません。',
    devBuildDownloadNote: '直近の CI 実行でパッケージ化され、開発用に署名されています。',
    commitLabel: 'コミット',
  },
  ko: {
    qrTitle: '[APP] 앱 랜딩 페이지',
    qrHint: '휴대폰으로 스캔하면 이 페이지가 열립니다.',
    about: '앱 정보',
    permissions: '권한',
    releaseNotes: '릴리스 노트',
    rawKeyLabel: '키',
    whyNoDescription: '이 플랫폼에서 앱이 사용합니다.',
    noPermissions: '선언된 권한이 없습니다.',
    versionLabel: '버전',
    buildLabel: '빌드',
    bundleIdLabel: '번들 ID',
    appIdLabel: '앱 ID',
    privacyLink: '개인정보 처리방침',
    supportLink: '지원',
    dependenciesLabel: '종속성',
    searchPlaceholder: '검색',
    searchClearLabel: '지우기',
    searchZeroResults: '[SEARCH_TERM]에 대한 결과가 없습니다',
    generatedLabel: '생성됨',
    sourceLink: '소스 코드',
    releaseLink: '릴리스',
    builtWith: 'Day로 제작',
    versionPickerLabel: '버전',
    devBuildInline: '[BRANCH]의 개발 빌드입니다. 불안정할 수 있습니다.',
    devBuildReleaseLink: '대신 [VERSION] 릴리스 받기',
    devBuildNoRelease: '아직 공개된 릴리스가 없습니다.',
    devBuildDownloadNote: '최근 CI 실행에서 패키징되었으며 개발용으로 서명되었습니다.',
    commitLabel: '커밋',
  },
  ms: {
    about: 'Tentang aplikasi',
    permissions: 'Kebenaran',
    releaseNotes: 'Nota keluaran',
    rawKeyLabel: 'Kunci',
    whyNoDescription: 'Digunakan oleh aplikasi pada platform ini.',
    noPermissions: 'Tiada kebenaran yang diisytiharkan.',
    versionLabel: 'Versi',
    buildLabel: 'Binaan',
    bundleIdLabel: 'ID bundel',
    appIdLabel: 'ID aplikasi',
    privacyLink: 'Privasi',
    supportLink: 'Sokongan',
    dependenciesLabel: 'Kebergantungan',
    searchPlaceholder: 'Cari',
    searchClearLabel: 'Kosongkan',
    searchZeroResults: 'Tiada hasil untuk [SEARCH_TERM]',
    generatedLabel: 'Dijana pada',
    sourceLink: 'Kod sumber',
    releaseLink: 'Keluaran',
    builtWith: 'Dibina dengan Day',
    versionPickerLabel: 'Versi',
    devBuildInline: 'Binaan pembangunan [BRANCH]. Boleh menjadi tidak stabil.',
    devBuildReleaseLink: 'Dapatkan keluaran [VERSION] sebaliknya',
    devBuildNoRelease: 'Belum ada keluaran diterbitkan.',
    devBuildDownloadNote: 'Dibungkus oleh larian CI terakhir dan ditandatangani untuk pembangunan.',
  },
  nl: {
    about: 'Over de app',
    permissions: 'Machtigingen',
    releaseNotes: 'Releaseopmerkingen',
    rawKeyLabel: 'Sleutel',
    whyNoDescription: 'Wordt door de app op dit platform gebruikt.',
    noPermissions: 'Geen gedeclareerde machtigingen.',
    versionLabel: 'Versie',
    buildLabel: 'Build',
    bundleIdLabel: 'Bundel-ID',
    appIdLabel: 'App-ID',
    privacyLink: 'Privacy',
    supportLink: 'Ondersteuning',
    dependenciesLabel: 'Afhankelijkheden',
    searchPlaceholder: 'Zoeken',
    searchClearLabel: 'Wissen',
    searchZeroResults: 'Geen resultaten voor [SEARCH_TERM]',
    generatedLabel: 'Gegenereerd op',
    sourceLink: 'Broncode',
    releaseLink: 'Release',
    builtWith: 'Gemaakt met Day',
    versionPickerLabel: 'Versie',
    devBuildInline: 'Ontwikkelbuild van [BRANCH]. Kan instabiel zijn.',
    devBuildReleaseLink: 'Download in plaats daarvan release [VERSION]',
    devBuildNoRelease: 'Er is nog geen release gepubliceerd.',
    devBuildDownloadNote: 'Verpakt door de laatste CI-run en ondertekend voor ontwikkeling.',
  },
  pl: {
    about: 'O aplikacji',
    permissions: 'Uprawnienia',
    releaseNotes: 'Informacje o wersji',
    rawKeyLabel: 'Klucz',
    whyNoDescription: 'Używane przez aplikację na tej platformie.',
    noPermissions: 'Brak zadeklarowanych uprawnień.',
    versionLabel: 'Wersja',
    buildLabel: 'Kompilacja',
    bundleIdLabel: 'Identyfikator pakietu',
    appIdLabel: 'Identyfikator aplikacji',
    privacyLink: 'Prywatność',
    supportLink: 'Pomoc',
    dependenciesLabel: 'Zależności',
    searchPlaceholder: 'Szukaj',
    searchClearLabel: 'Wyczyść',
    searchZeroResults: 'Brak wyników dla [SEARCH_TERM]',
    generatedLabel: 'Wygenerowano',
    sourceLink: 'Kod źródłowy',
    releaseLink: 'Wydanie',
    builtWith: 'Utworzono za pomocą Day',
    versionPickerLabel: 'Wersja',
    devBuildInline: 'Kompilacja rozwojowa gałęzi [BRANCH]. Może być niestabilna.',
    devBuildReleaseLink: 'Pobierz zamiast tego wydanie [VERSION]',
    devBuildNoRelease: 'Nie opublikowano jeszcze żadnego wydania.',
    devBuildDownloadNote: 'Spakowane w ostatnim przebiegu CI i podpisane na potrzeby rozwoju.',
  },
  pt: {
    about: 'Sobre',
    permissions: 'Permissões',
    releaseNotes: 'Notas da versão',
    rawKeyLabel: 'Chave',
    whyNoDescription: 'Usado pelo app nesta plataforma.',
    noPermissions: 'Sem permissões declaradas.',
    versionLabel: 'Versão',
    buildLabel: 'Build',
    bundleIdLabel: 'ID do bundle',
    appIdLabel: 'ID do aplicativo',
    privacyLink: 'Privacidade',
    supportLink: 'Suporte',
    dependenciesLabel: 'Dependências',
    searchPlaceholder: 'Pesquisar',
    searchClearLabel: 'Limpar',
    searchZeroResults: 'Sem resultados para [SEARCH_TERM]',
    generatedLabel: 'Gerado em',
    sourceLink: 'Código-fonte',
    releaseLink: 'Lançamento',
    builtWith: 'Criado com Day',
    versionPickerLabel: 'Versão',
    devBuildInline: 'Compilação de desenvolvimento de [BRANCH]. Pode ser instável.',
    devBuildReleaseLink: 'Baixe a versão [VERSION] em vez disso',
    devBuildNoRelease: 'Nenhuma versão foi publicada ainda.',
    devBuildDownloadNote: 'Empacotado pela última execução de CI e assinado para desenvolvimento.',
  },
  ru: {
    about: 'О приложении',
    permissions: 'Разрешения',
    releaseNotes: 'Заметки о выпуске',
    rawKeyLabel: 'Ключ',
    whyNoDescription: 'Используется приложением на этой платформе.',
    noPermissions: 'Разрешения не заявлены.',
    versionLabel: 'Версия',
    buildLabel: 'Сборка',
    bundleIdLabel: 'ID пакета',
    appIdLabel: 'ID приложения',
    privacyLink: 'Конфиденциальность',
    supportLink: 'Поддержка',
    dependenciesLabel: 'Зависимости',
    searchPlaceholder: 'Поиск',
    searchClearLabel: 'Очистить',
    searchZeroResults: 'Нет результатов для [SEARCH_TERM]',
    generatedLabel: 'Создано',
    sourceLink: 'Исходный код',
    releaseLink: 'Выпуск',
    builtWith: 'Создано с помощью Day',
    versionPickerLabel: 'Версия',
    devBuildInline: 'Сборка для разработки ветки [BRANCH]. Может быть нестабильной.',
    devBuildReleaseLink: 'Скачать вместо неё выпуск [VERSION]',
    devBuildNoRelease: 'Ни один выпуск ещё не опубликован.',
    devBuildDownloadNote: 'Собрано последним запуском CI и подписано для разработки.',
    commitLabel: 'Коммит',
  },
  th: {
    about: 'เกี่ยวกับแอป',
    permissions: 'สิทธิ์',
    releaseNotes: 'บันทึกประจำรุ่น',
    rawKeyLabel: 'คีย์',
    whyNoDescription: 'แอปใช้งานบนแพลตฟอร์มนี้',
    noPermissions: 'ไม่มีสิทธิ์ที่ประกาศไว้',
    versionLabel: 'เวอร์ชัน',
    buildLabel: 'บิลด์',
    bundleIdLabel: 'รหัสบันเดิล',
    appIdLabel: 'รหัสแอปพลิเคชัน',
    privacyLink: 'ความเป็นส่วนตัว',
    supportLink: 'การสนับสนุน',
    dependenciesLabel: 'การอ้างอิง',
    searchPlaceholder: 'ค้นหา',
    searchClearLabel: 'ล้าง',
    searchZeroResults: 'ไม่พบผลลัพธ์สำหรับ [SEARCH_TERM]',
    generatedLabel: 'สร้างเมื่อ',
    sourceLink: 'ซอร์สโค้ด',
    releaseLink: 'รุ่น',
    builtWith: 'สร้างด้วย Day',
    versionPickerLabel: 'เวอร์ชัน',
    devBuildInline: 'บิลด์สำหรับนักพัฒนาของ [BRANCH] อาจไม่เสถียร',
    devBuildReleaseLink: 'ดาวน์โหลดรุ่น [VERSION] แทน',
    devBuildNoRelease: 'ยังไม่มีการเผยแพร่รุ่นใด',
    devBuildDownloadNote: 'แพ็กโดยการรัน CI ล่าสุดและเซ็นสำหรับการพัฒนา',
    commitLabel: 'คอมมิต',
  },
  tr: {
    about: 'Uygulama hakkında',
    permissions: 'İzinler',
    releaseNotes: 'Sürüm notları',
    rawKeyLabel: 'Anahtar',
    whyNoDescription: 'Uygulama tarafından bu platformda kullanılır.',
    noPermissions: 'Bildirilen izin yok.',
    versionLabel: 'Sürüm',
    buildLabel: 'Derleme',
    bundleIdLabel: 'Paket kimliği',
    appIdLabel: 'Uygulama kimliği',
    privacyLink: 'Gizlilik',
    supportLink: 'Destek',
    dependenciesLabel: 'Bağımlılıklar',
    searchPlaceholder: 'Ara',
    searchClearLabel: 'Temizle',
    searchZeroResults: '[SEARCH_TERM] için sonuç bulunamadı',
    generatedLabel: 'Oluşturulma',
    sourceLink: 'Kaynak kodu',
    releaseLink: 'Yayın',
    builtWith: 'Day ile oluşturuldu',
    versionPickerLabel: 'Sürüm',
    devBuildInline: '[BRANCH] dalının geliştirme derlemesi. Kararsız olabilir.',
    devBuildReleaseLink: 'Bunun yerine [VERSION] sürümünü indirin',
    devBuildNoRelease: 'Henüz bir sürüm yayımlanmadı.',
    devBuildDownloadNote: 'Son CI çalıştırmasında paketlendi ve geliştirme için imzalandı.',
  },
  uk: {
    about: 'Про застосунок',
    permissions: 'Дозволи',
    releaseNotes: 'Примітки до випуску',
    rawKeyLabel: 'Ключ',
    whyNoDescription: 'Використовується застосунком на цій платформі.',
    noPermissions: 'Дозволи не оголошено.',
    versionLabel: 'Версія',
    buildLabel: 'Збірка',
    bundleIdLabel: 'ID пакета',
    appIdLabel: 'ID застосунку',
    privacyLink: 'Конфіденційність',
    supportLink: 'Підтримка',
    dependenciesLabel: 'Залежності',
    searchPlaceholder: 'Пошук',
    searchClearLabel: 'Очистити',
    searchZeroResults: 'Немає результатів для [SEARCH_TERM]',
    generatedLabel: 'Створено',
    sourceLink: 'Вихідний код',
    releaseLink: 'Випуск',
    builtWith: 'Створено за допомогою Day',
    versionPickerLabel: 'Версія',
    devBuildInline: 'Збірка для розробки гілки [BRANCH]. Може бути нестабільною.',
    devBuildReleaseLink: 'Завантажте натомість випуск [VERSION]',
    devBuildNoRelease: 'Жодного випуску ще не опубліковано.',
    devBuildDownloadNote: 'Спаковано останнім запуском CI та підписано для розробки.',
    commitLabel: 'Коміт',
  },
  vi: {
    about: 'Giới thiệu về ứng dụng',
    permissions: 'Quyền',
    releaseNotes: 'Ghi chú phát hành',
    rawKeyLabel: 'Khóa',
    whyNoDescription: 'Được ứng dụng sử dụng trên nền tảng này.',
    noPermissions: 'Không có quyền nào được khai báo.',
    versionLabel: 'Phiên bản',
    buildLabel: 'Bản dựng',
    bundleIdLabel: 'ID gói',
    appIdLabel: 'ID ứng dụng',
    privacyLink: 'Quyền riêng tư',
    supportLink: 'Hỗ trợ',
    dependenciesLabel: 'Phụ thuộc',
    searchPlaceholder: 'Tìm kiếm',
    searchClearLabel: 'Xóa',
    searchZeroResults: 'Không có kết quả cho [SEARCH_TERM]',
    generatedLabel: 'Được tạo lúc',
    sourceLink: 'Mã nguồn',
    releaseLink: 'Bản phát hành',
    builtWith: 'Được tạo bằng Day',
    versionPickerLabel: 'Phiên bản',
    devBuildInline: 'Bản dựng phát triển của [BRANCH]. Có thể không ổn định.',
    devBuildReleaseLink: 'Tải bản phát hành [VERSION] thay thế',
    devBuildNoRelease: 'Chưa có bản phát hành nào được công bố.',
    devBuildDownloadNote: 'Được đóng gói bởi lần chạy CI gần nhất và ký cho mục đích phát triển.',
  },
  zh: {
    qrTitle: '[APP] 应用的主页',
    qrHint: '用手机扫描即可打开此页面。',
    about: '关于',
    permissions: '权限',
    releaseNotes: '版本说明',
    rawKeyLabel: '键',
    whyNoDescription: '此平台上的应用会使用。',
    noPermissions: '未声明任何权限。',
    versionLabel: '版本',
    buildLabel: '构建',
    bundleIdLabel: 'Bundle ID',
    appIdLabel: '应用 ID',
    privacyLink: '隐私',
    supportLink: '支持',
    dependenciesLabel: '依赖项',
    searchPlaceholder: '搜索',
    searchClearLabel: '清除',
    searchZeroResults: '没有 [SEARCH_TERM] 的结果',
    generatedLabel: '生成时间',
    sourceLink: '源代码',
    releaseLink: '发行版',
    builtWith: '使用 Day 构建',
    galleryLink: '图库',
    galleryHeading: '截图',
    galleryBlurb: '这些截图由持续集成的 [DAYSCRIPT] 演练针对每个工具包自动截取。',
    versionPickerLabel: '版本',
    devBuildInline: '[BRANCH] 的开发版构建，可能不稳定。',
    devBuildReleaseLink: '改为获取 [VERSION] 发行版',
    devBuildNoRelease: '尚未发布任何版本。',
    devBuildDownloadNote: '由最近一次 CI 运行打包，并以开发身份签名。',
    commitLabel: '提交',
  },
  'zh-Hant': {
    about: '關於',
    permissions: '權限',
    releaseNotes: '版本資訊',
    rawKeyLabel: '鍵',
    whyNoDescription: '此平台上的應用程式會使用。',
    noPermissions: '未宣告任何權限。',
    versionLabel: '版本',
    buildLabel: '組建',
    bundleIdLabel: 'Bundle ID',
    appIdLabel: '應用程式 ID',
    privacyLink: '隱私權',
    supportLink: '支援',
    dependenciesLabel: '相依性',
    searchPlaceholder: '搜尋',
    searchClearLabel: '清除',
    searchZeroResults: '沒有 [SEARCH_TERM] 的結果',
    generatedLabel: '產生時間',
    sourceLink: '原始碼',
    releaseLink: '發行版',
    builtWith: '使用 Day 建置',
    versionPickerLabel: '版本',
    devBuildInline: '[BRANCH] 的開發版組建，可能不穩定。',
    devBuildReleaseLink: '改為取得 [VERSION] 發行版',
    devBuildNoRelease: '尚未發布任何版本。',
    devBuildDownloadNote: '由最近一次 CI 執行打包，並以開發身分簽署。',
    commitLabel: '提交',
  },
};

export function uiStrings(locale: string): UIStrings {
  // English first, then each subtag prefix from broadest to narrowest, so the more specific
  // table always wins the key: "zh-Hant-TW" picks up "zh" and then "zh-Hant". The order is the
  // whole point — apply "zh" last and Traditional Chinese pages render the Simplified strings.
  const parts = locale.split('-');
  let out: UIStrings = { ...EN };
  for (let i = 1; i <= parts.length; i++) {
    out = { ...out, ...(TABLES[parts.slice(0, i).join('-')] ?? {}) };
  }
  return out;
}
